# -*- coding: utf-8 -*-
"""src/item.h -- what a press on the top row writes, for the cells no command
has been built for yet.

    python tools/item_table.py $(cat tmp/branch/line.txt) > src/item.h

src/prompt.h holds the line a *menu* item comes up with; this holds what the
items **on that line** write when they are pressed.  Both are the original's
own bytes.

tools/branchstr.sh drives the emulator through every menu x item x button and
takes **two** shots on each: one when the menu item has come up and one after
the press on the top row.  What lies between the two markers in the log is
exactly what that press wrote -- so nothing has to be guessed about where the
screen before it ended, and the table is a difference, not a whole line.  The
original writes over part of the row and leaves the rest, which is why that
matters.

The left and right buttons are kept apart, because a few cells answer them
differently.

**Nothing here is believed until the pixels agree**: tools/branchport.mjs and
tools/branchdiff.py put the port's screen beside the original's, and a branch
that is not at nought is one this got wrong.
"""
import os
import re
import sys

sys.stdout.reconfigure(encoding='utf-8', newline='\n')

LIST = 'tmp/branch/list.txt'
LOG = os.environ.get('BRANCHLOG', 'tmp/branch/rawstr.txt')


def deltas():
    """{branch number: [(col, row, fg, bg, raw), ...] written by the press}"""
    out, held, arming = {}, [], None
    for line in open(LOG, encoding='latin-1'):
        m = re.search(r'\[shot\] .*?(pre|mark)(\d+)\.raw', line)
        if m:
            if m.group(1) == 'pre':
                arming = int(m.group(2))
            elif arming == int(m.group(2)):
                out[arming] = held
                arming = None
            held = []
            continue
        if arming is None or '[bp]' not in line or line.count('"') < 2:
            continue
        f = line.split()
        if len(f) < 15:
            continue
        try:
            col, row = int(f[8], 16), int(f[9], 16)
            fg, bg = int(f[10], 16), int(f[11], 16)
        except ValueError:
            continue
        text = line[line.index('"'):].rstrip('\n')
        held.append((col, row, fg, bg,
                     text[text.index('"') + 1:text.rindex('"')].encode('latin-1')))
    return out


# What the original puts up while it is thinking and takes away again.  It is
# never on the screen anyone looks at, so it is not part of it.
#
#   ※お待ち下さい※            over the top line
#   描画中断 [ｽﾍﾟｰｽｷｰ],ﾏｳｽ(R)  in the strip along the bottom, while it redraws
#
# The second one matters more than it looks: the strip that comes back is
# painted as well as written, and only the writing is in the log, so replaying
# the strings alone leaves the first cell of it standing.
REDREW = b' \x95`\x89\xe6\x92\x86\x92f [\xbd\xcd\xdf\xb0\xbd\xb7\xb0],\xcf\xb3\xbd(R) '
GONE = (
    b'\x81\x96\x82\xa8\x91\xd2\x82\xbf\x89\xba\x82\xb3\x82\xa2\x81\x96',
    REDREW,
)


def literal(raw, indent='      ', width=58):
    chunks, cur, cur_hex = [], '', False
    for ch in raw:
        hexed = not (0x20 <= ch < 0x7f) or ch in (0x22, 0x5c)
        if cur and hexed != cur_hex:
            chunks.append('"%s"' % cur)
            cur = ''
        cur += '\\x%02x' % ch if hexed else chr(ch)
        cur_hex = hexed
    if cur:
        chunks.append('"%s"' % cur)
    if not chunks:
        return '""'             # the original wrote an empty string
    lines, line = [], ''
    for c in chunks:
        if line and len(line) + 1 + len(c) > width:
            lines.append(line)
            line = c
        else:
            line = line + ' ' + c if line else c
    if line:
        lines.append(line)
    return (' \\\n' + indent).join(lines)


want = set(int(a) for a in sys.argv[1:] if a.isdigit())
log = deltas()
lines = open(LIST, encoding='utf-8').read().strip().split('\n')

print('''/* src/item.h -- what a press on a cell of a command's top row writes.
 *
 * Generated by tools/item_table.py out of what tools/branchstr.sh captured.
 * Do not edit by hand -- run the tool again.
 *
 * src/prompt.h is the line the *menu* item comes up with; this is the writes
 * the cells on that line make when they are pressed.  They are a difference,
 * not a whole line: the original writes over part of the row and leaves the
 * rest, so src/ui.c replays them **on top of** the prompt.
 *
 * **This is the line, not the behaviour.**  It covers the cells no command
 * has been built for yet, so that the screen is the original's while the work
 * goes on; as each one grows its own code in src/cmd.c it claims the press
 * and drops out of here.
 */
#ifndef JW_ITEM_H
#define JW_ITEM_H

typedef struct {
    int command;                /* the menu item, 1 to 30, or 0 to end */
    int item;                   /* which cell of the top row was pressed */
    int right;                  /* 1 if that was the right button */
    int col, row, fg, bg;
    const char *text;
} JwItem;

static const JwItem JW_ITEM[] = {''')

n_out, n_empty = 0, 0
for i, line in enumerate(lines):
    n = i + 1
    if want and n not in want:
        continue
    menu, item, button = line.split()[:3]
    if item == '0':
        continue
    got = log.get(n, [])
    rows = [r for r in got if r[4] not in GONE]
    if rows and any(r[4] == REDREW for r in got):
        # row 0 is no row: the marker that this press redrew the drawing.
        rows.insert(0, (1, 0, 7, 0, REDREW))
    if not rows:
        print('    /* branch %d (menu %s item %s %s): the press wrote nothing */'
              % (n, menu, item, button))
        n_empty += 1
        continue
    print('    /* branch %d: menu %s item %s %s */' % (n, menu, item, button))
    for col, row, fg, bg, raw in rows:
        print('    { %2s, %2s, %d, %2d, %d, %d, 0x%04X,\n      %s },'
              % (menu, item, 1 if button == 'right' else 0, col, row, fg, bg,
                 literal(raw)))
        n_out += 1

print('''    { 0, 0, 0, 0, 0, 0, 0, 0 }
};

#endif''')
sys.stderr.write('%d writes, %d branches wrote nothing\n' % (n_out, n_empty))
