"""Turn what tools/menus.sh captured into the table src/ui.c draws.

Run it after `sh tools/menus.sh`; it writes src/prompt.h.  Nothing here is
invented: every piece is a string the original wrote into the top line after
the menu item was picked, with the column it wrote it at.

    sh tools/menus.sh
    python tools/menus_table.py
"""
import sys

B = chr(92)
AFTER = 43_000_000          # past the click and the "please wait" flash


def escape(s):
    out = ['"']
    for c in s:
        if c == '"' or c == B:
            out.append(B + c)
        elif c == '?':
            out.append(B + '?')     # no trigraphs
        elif 0x20 <= ord(c) < 0x7f:
            out.append(c)
        else:
            out.append(B + 'x%02x' % ord(c))
            out.append('" "')       # stop the escape swallowing what follows
    out.append('"')
    return ''.join(out).replace('"" ', '').replace(' ""', '')


def pieces(n):
    out = []
    for line in open('tmp/menus/s%d.txt' % n, encoding='latin-1'):
        f = line.split()
        if len(f) < 15 or f[0] != '[bp]' or int(f[3]) < AFTER:
            continue
        col, row = int(f[8], 16), int(f[9], 16)
        fg, bg = int(f[10], 16), int(f[11], 16)
        if line.count('"') < 2:
            continue        # a line the dump could not quote
        s = line[line.index('"') + 1:line.rindex('"')]
        if row > 3:
            continue
        out.append((col, row, fg, bg, s))
    return out


rows = [pieces(n) for n in range(1, 31)]
wide = max(len(r) for r in rows)

f = open('src/prompt.h', 'w', encoding='utf-8', newline='\n')
f.write('''/* What the original writes along the top when a menu item is picked.
 *
 * Generated by tools/menus_table.py out of what tools/menus.sh captured: the
 * emulator clicks each of the thirty items in turn and every string the
 * original then wrote into row 1 is kept, with the column it went to.  Do not
 * edit by hand -- run the two tools again.
 *
 * Some of the lines carry numbers that belong to the program's state (the
 * offset in 面取, the spacing in 複線, how many cuts are left in 包絡).  Those
 * are here as the original had them with SAMPLE2 loaded and nothing done yet,
 * which is the screen tools/menus.sh compares against.
 */
#ifndef JW_PROMPT_H
#define JW_PROMPT_H

typedef struct {
    int col;                    /* one-based character cell, or 0 to end */
    int row;                    /* 1 is the top line; 2 and 3 are the band
                                 * under it, which a few commands write in */
    int fg;
    int bg;                     /* 0 paints black behind, 0xffff fills with fg
                                 * and writes the letters over it in black */
    const char *text;
} JwPrompt;

static const JwPrompt JW_PROMPT[30][%d] = {
''' % (wide + 1))
for n, r in enumerate(rows, 1):
    f.write('    {   /* %2d */\n' % n)
    for col, row, fg, bg, s in r:
        f.write('        { %2d, %d, %d, 0x%04x, %s },\n'
                % (col, row, fg, bg, escape(s)))
    f.write('        { 0, 0, 0, 0, 0 },\n    },\n')
f.write('};\n\n#endif\n')
f.close()
print('wrote src/prompt.h  (%d commands, at most %d pieces)' % (len(rows), wide))
