# -*- coding: utf-8 -*-
"""src/optplan.h -- the lines ｵﾌﾟｼｮﾝ ①建具平面 writes once a shape is picked.

    sh tools/optpick.sh 1 250 40 300 139 350 200
    python tools/optplan_table.py > src/optplan.h

tools/optpick.sh presses ｵﾌﾟｼｮﾝ, then ①建具平面, then the points given, and
shoots after each; this turns the strings between two shots into a table in
src/stage.h's shape.  The presses above are the road:

    1  a shape's cell   `・基準線(L) ２点(R) |①内法寸法|②基準線との間隔|`
                        with `[BS]前項` at column 73
    2  the 基準線       `[ESC] ◇位置 (L)free (R)Read|①間隔反転|②建具心変
                         |③基準点変|④建具反転|⑤左右|`
    3  the position     the fitting goes in and the line goes back to 1's

Only what it writes into the **top line** is kept; the two numbers in the
band (1800.00 at column 29 and 0.00 at column 42, then 0.00, 中心 and 内法 at
32, 44 and 55) are values and src/ui.c writes them from the state.
"""
import io
import os
import re
import sys

sys.stdout.reconfigure(encoding='utf-8', newline='\n')

LOG = os.environ.get('OPTLOG', 'tmp/optpick/raw.txt')
WAIT = b'\x81\x96\x82\xa8\x91\xd2\x82\xbf\x89\xba\x82\xb3\x82\xa2\x81\x96'


def literal(raw, indent='      ', width=58):
    chunks, cur, cur_hex = [], '', False
    for ch in raw:
        hexed = not (0x20 <= ch < 0x7f) or ch in (0x22, 0x5c)
        if cur and hexed != cur_hex:
            chunks.append('"%s"' % cur)
            cur = ''
        cur += '\\x%02x' % ch if hexed else chr(ch)
        cur_hex = hexed
    if cur:
        chunks.append('"%s"' % cur)
    if not chunks:
        return '""'
    lines, line = [], ''
    for c in chunks:
        if line and len(line) + 1 + len(c) > width:
            lines.append(line)
            line = c
        else:
            line = line + ' ' + c if line else c
    if line:
        lines.append(line)
    return (' \\\n' + indent).join(lines)


held, stages = [], {}
for line in open(LOG, encoding='latin-1'):
    m = re.search(r'\[shot\] .*?s(\d+)\.raw', line)
    if m:
        stages[int(m.group(1))] = held
        held = []
        continue
    if '[bp]' not in line or line.count('"') < 2:
        continue
    f = line.split()
    if len(f) < 15:
        continue
    try:
        col, row = int(f[8], 16), int(f[9], 16)
        fg, bg = int(f[10], 16), int(f[11], 16)
    except ValueError:
        continue
    text = line[line.index('"'):].rstrip('\n')
    held.append((col, row, fg, bg,
                 text[text.index('"') + 1:text.rindex('"')].encode('latin-1')))

print('''/* src/optplan.h -- ｵﾌﾟｼｮﾝ ①建具平面's road, as the original writes it.
 *
 * Generated by tools/optplan_table.py out of what tools/optpick.sh captured.
 * Do not edit by hand -- run the two again.
 */
#ifndef JW_OPTPLAN_H
#define JW_OPTPLAN_H

/* Where the road is, once one of the sixteen shapes has been picked.
 * JwUi.opt_stage holds one of these. */
#define JW_OPT_PLAN   1         /* the sixteen shapes are up */
#define JW_OPT_BASE   2         /* a shape picked: 基準線(L) ２点(R) … */
#define JW_OPT_WHERE  3         /* a line picked: ◇位置 (L)free (R)Read … */
#define JW_OPT_BASE2  4         /* the same as BASE, once one has gone in */

typedef struct {
    int stage;
    int col, fg, bg;
    const char *text;
} JwOptPlan;

static const JwOptPlan JW_OPTPLAN[] = {''')

# Press 0 is the sixteen shapes going up, which src/item.h already holds.
# Presses 1 and 3 put the **same** line up and do not write the same thing:
# the first leaves out its [ESC], because the 建具選択 line it replaces had one
# already, and the second writes the lot.  So they are two stages here, and
# src/main_wasm.c goes to the second one after a fitting has gone in.
WANT = {1: 2, 2: 3, 3: 4}       # which press gives which stage

n = 0
for press in sorted(WANT):
    rows = [r for r in stages.get(press, []) if r[1] == 1 and r[4] != WAIT]
    if not rows:
        continue
    print('    /* press %d */' % press)
    for col, row, fg, bg, raw in rows:
        print('    { %d, %2d, %d, 0x%04X,\n      %s },'
              % (WANT[press], col, fg, bg, literal(raw)))
        n += 1
print('''    { 0, 0, 0, 0, 0 }
};

#endif''')
sys.stderr.write('%d writes\n' % n)
