"""What the original says a **modified** right button would snap to.

Short strings sit in the band beside the counts, at columns 17 and 22 of row 2.
They are not part of what a menu item puts up: they appear only once the
pointer is over the drawing **and a modifier key is down**, and they say what
that key would make 読取 take -- 鉛直･/円周点 for ／ with [CTRL], 線・円上点
for [SHIFT], 中心点・Ａ点 for [GRPH].  So they follow the mouse and the keys,
not the stage.

This picks each item, holds one modifier, moves the pointer into the drawing
and keeps whatever the original then wrote to those cells.

    python tools/snap_table.py         # writes src/snap.h

Ninety runs of the original -- thirty items times three keys -- so it takes
some minutes.  The table used to be captured with nothing held, which looked
like it worked: dosv_emu_cpp did not answer INT 16h AH=12h until 2026-09-18 and
JW_CAD read the caller's own buffer as the shift state, with the Ctrl bit set.
Every row of it was a [CTRL] row (RESUME.md 4.19).
"""
import os
import re
import subprocess
import sys

B = chr(92)
EMU = '../dosv_emu_cpp/dosemu.exe'
AFTER = 42_000_000
# The order the generated table is indexed in.  `alt` is what the emulator's
# script calls [GRPH]; a J-3100 keyboard's key is the same bit.
KEYS = ('shift', 'ctrl', 'alt')


def escape(s):
    out = ['"']
    for c in s:
        if c in ('"', B):
            out.append(B + c)
        elif c == '?':
            out.append(B + '?')
        elif 0x20 <= ord(c) < 0x7f:
            out.append(c)
        else:
            out.append(B + 'x%02x' % ord(c))
            out.append('" "')
    out.append('"')
    return ''.join(out).replace('"" ', '').replace(' ""', '')


def capture(n, mod):
    mx, row = (90, n - 1) if n <= 15 else (30, n - 16)
    my = 64 + 16 * row + 8
    # The key goes down **after** the item is picked and before the pointer
    # moves in: the original looks at the keys as it works out what to write,
    # so it only has to be held while the pointer is over the drawing.
    open('tmp/snap.txt', 'w').write(
        'wait 40000000\nmouse %d %d\nwait 2000000\nclick left\nwait 24000000\n'
        'mods %s\nmouse 300 200\nwait 20000000\nmods none\n' % (mx, my, mod))
    out = subprocess.run(
        [EMU, '--root', 'orig', '--font-ank', 'font/JWANK16.FNT',
         '--font-kanji', 'font/JWKAN16.FNT', '--script', 'tmp/snap.txt',
         'orig/JW_CADV.EXE', 'SAMPLE0.JWC'],
        capture_output=True,
        env=dict(os.environ, DOSEMU_BP='+0DEF:23C5', DOSEMU_BPSTR='2',
                 DOSEMU_BPN='20000')).stdout.decode('latin-1')
    last = {}
    for line in out.splitlines():
        f = line.split()
        if len(f) < 15 or f[0] != '[bp]' or line.count('"') < 2:
            continue
        if int(f[3]) < AFTER:
            continue
        col, r = int(f[8], 16), int(f[9], 16)
        if r != 2 or col not in (17, 22):
            continue
        last[col] = line[line.index('"') + 1:line.rindex('"')]
    return last


HEAD = '''/* What a **modified** read would take, per command and per key.
 *
 * Generated by tools/snap_table.py.  Two strings in the band beside the
 * counts, at columns 17 and 22.  They go on last: a stage writes spaces at
 * column 17 on a black background, and those reach across column 22.
 *
 * They are there only while the pointer is over the drawing **and a modifier
 * key is held**.  With nothing held the original writes the spaces and leaves
 * the band black, so src/ui.c draws them only for the key that is down.  The
 * three rows are [SHIFT], [CTRL] and [GRPH], which JW_SNAP_KEY names; a 0
 * means the original wrote nothing there, and [SHIFT] and [GRPH] write one
 * string at column 17 wide enough to reach across column 22.
 *
 * The whole table looked unconditional until 2026-09-18: dosv_emu_cpp did not
 * answer INT 16h AH=12h, JW_CAD read the caller's own buffer as the shift
 * state, and the bit that came back set was Ctrl -- so every captured run
 * behaved as though Ctrl were held.  See RESUME.md 4.19.
 */
#ifndef JW_SNAP_H
#define JW_SNAP_H

/* The rows of JW_SNAP, in the order src/read.h's JW_MOD_* are worth naming. */
#define JW_SNAP_SHIFT 0
#define JW_SNAP_CTRL  1
#define JW_SNAP_GRPH  2

static const char *const JW_SNAP[3][30][2] = {
'''


def main():
    if not os.path.exists(EMU):
        sys.exit('build dosv_emu_cpp first')
    rows = {}
    for mod in KEYS:
        for n in range(1, 31):
            rows[mod, n] = capture(n, mod)
            print('%-5s %2d %s' % (mod, n, rows[mod, n]), flush=True)
    f = open('src/snap.h', 'w', encoding='utf-8', newline='\n')
    f.write(HEAD)
    for mod in KEYS:
        f.write('  {  /* %s */\n' % mod)
        for n in range(1, 31):
            a, b = rows[mod, n].get(17, ''), rows[mod, n].get(22, '')
            f.write('    { %s, %s },  /* %2d */\n'
                    % (escape(a) if a else '0', escape(b) if b else '0', n))
        f.write('  },\n')
    f.write('};\n\n#endif\n')
    f.close()
    print('wrote src/snap.h')


main()
