"""What the original writes when a modified read is waiting for its second press.

[SHIFT] and [GRPH] do not take a point on the first press: they pick what to
work from and then ask again, with a line of their own along the top and a word
in the band.  Those strings are read out of the running original rather than
typed in here, the way tools/esc_table.py does it for [ESC].

    python tools/snapmsg.py              # writes src/snapmsg.h

Two runs: [SHIFT] pressed on SAMPLE0's line 4, which puts it into 線･円上点
スナップ, and [GRPH] pressed on the end of line 5, which puts it into
２点間中心.  Everything either run writes to rows 1 and 2 after the press is
kept, with the cell it went to.
"""
import os
import subprocess
import sys

B = chr(92)
EMU = '../dosv_emu_cpp/dosemu.exe'
# The press happens around 72,000,000; nothing before it belongs to the mode.
AFTER = 70_000_000
# mod, where to press, and the name the generated header gives it.
CASES = (('shift', 300, 402, 'JW_SNAP_ON'),
         ('alt', 232, 157, 'JW_SNAP_MID'))


def escape(s):
    out = ['"']
    for c in s:
        if c in ('"', B):
            out.append(B + c)
        elif c == '?':
            out.append(B + '?')
        elif 0x20 <= ord(c) < 0x7f:
            out.append(c)
        else:
            out.append(B + 'x%02x' % ord(c))
            out.append('" "')
    out.append('"')
    return ''.join(out).replace('"" ', '').replace(' ""', '')


def capture(mod, x, y):
    open('tmp/snapmsg.txt', 'w').write(
        'wait 40000000\nmouse 90 104\nwait 2000000\nclick left\nwait 24000000\n'
        'mods %s\nmouse %d %d\nwait 3000000\ndown right\nwait 3000000\n'
        'up right\nwait 20000000\n' % (mod, x, y))
    out = subprocess.run(
        [EMU, '--root', 'orig', '--font-ank', 'font/JWANK16.FNT',
         '--font-kanji', 'font/JWKAN16.FNT', '--script', 'tmp/snapmsg.txt',
         'orig/JW_CADV.EXE', 'SAMPLE0.JWC'],
        capture_output=True,
        env=dict(os.environ, DOSEMU_BP='+0DEF:23C5', DOSEMU_BPSTR='2',
                 DOSEMU_BPN='20000')).stdout.decode('latin-1')
    wrote = []
    for line in out.splitlines():
        f = line.split()
        if len(f) < 15 or f[0] != '[bp]' or line.count('"') < 2:
            continue
        if int(f[3]) < AFTER:
            continue
        col, row = int(f[8], 16), int(f[9], 16)
        # Row 1 only.  The original does write to row 2 on the way in -- it
        # wipes the key's words with fourteen spaces at column 17 and leaves
        # サーチ at column 18 -- and then **blacks the whole band** over them,
        # which a log of strings cannot show.  The screen can: with the mode
        # up, every pixel of y17..31 from x122 to x638 is black and only the
        # frame at x639 is lit.  So the band is a fill, not a string, and
        # drawing what was written here would put サーチ back on the screen.
        if row != 1:
            continue
        wrote.append((col, row, line[line.index('"') + 1:line.rindex('"')]))
    return wrote


HEAD = '''/* src/snapmsg.h -- what a modified read writes while it waits.

Generated by tools/snapmsg.py, out of the running original.

A press with [SHIFT] or [GRPH] held does not always take a point: it picks a
line or a circle, or a first point, and then asks again.  While it is asking,
the original **blacks the whole top line** and writes two pieces over it -- the
word [ESC] at column 1 and the mode's own line at column 8.  It blacks the
band beside the counts as well, x122 to x638 of y17..31, over the wipe and
the サーチ it wrote there; capture() says how that was settled.

The rows below are exactly what the original wrote, cell by cell.
 */
#ifndef JW_SNAPMSG_H
#define JW_SNAPMSG_H

/* One string and where it goes: column, row, both one-based. */
typedef struct {
    int mode;                   /* JwCmd.snap: JW_SNAP_ON or JW_SNAP_MID */
    int col, row;
    const char *text;
} JwSnapMsg;

static const JwSnapMsg JW_SNAPMSG[] = {
'''


def main():
    if not os.path.exists(EMU):
        sys.exit('build dosv_emu_cpp first')
    f = open('src/snapmsg.h', 'w', encoding='utf-8', newline='\n')
    f.write(HEAD)
    for mod, x, y, name in CASES:
        for col, row, text in capture(mod, x, y):
            f.write('    { %s, %2d, %d, %s },\n'
                    % (name, col, row, escape(text)))
            print('%-5s c%-3d r%d %s' % (mod, col, row, ascii(text)), flush=True)
    f.write('    { 0, 0, 0, 0 },\n};\n\n#endif\n')
    f.close()
    print('wrote src/snapmsg.h')


main()
