"""What the original says the right button would snap to.

Two short strings sit in the band beside the counts, at columns 17 and 22.
They are not part of what a menu item puts up: they only appear once the
pointer is over the drawing, and they say what 読取 would take there -- 円周点
for ／, 円周1/4点 for □ and ○.  So they follow the mouse, not the stage.

This picks each item, moves the pointer into the drawing and keeps what the
original then wrote to those two cells.

    python tools/snap_table.py         # writes src/snap.h
"""
import os
import re
import subprocess
import sys

B = chr(92)
EMU = '../dosv_emu_cpp/dosemu.exe'
AFTER = 42_000_000


def escape(s):
    out = ['"']
    for c in s:
        if c in ('"', B):
            out.append(B + c)
        elif c == '?':
            out.append(B + '?')
        elif 0x20 <= ord(c) < 0x7f:
            out.append(c)
        else:
            out.append(B + 'x%02x' % ord(c))
            out.append('" "')
    out.append('"')
    return ''.join(out).replace('"" ', '').replace(' ""', '')


def capture(n):
    mx, row = (90, n - 1) if n <= 15 else (30, n - 16)
    my = 64 + 16 * row + 8
    open('tmp/snap.txt', 'w').write(
        'wait 40000000\nmouse %d %d\nwait 2000000\nclick left\nwait 24000000\n'
        'mouse 300 200\nwait 20000000\n' % (mx, my))
    out = subprocess.run(
        [EMU, '--root', 'orig', '--font-ank', 'font/JWANK16.FNT',
         '--font-kanji', 'font/JWKAN16.FNT', '--script', 'tmp/snap.txt',
         'orig/JW_CADV.EXE', 'SAMPLE0.JWC'],
        capture_output=True,
        env=dict(os.environ, DOSEMU_BP='+0DEF:23C5', DOSEMU_BPSTR='2',
                 DOSEMU_BPN='20000')).stdout.decode('latin-1')
    last = {}
    for line in out.splitlines():
        f = line.split()
        if len(f) < 15 or f[0] != '[bp]' or line.count('"') < 2:
            continue
        if int(f[3]) < AFTER:
            continue
        col, r = int(f[8], 16), int(f[9], 16)
        if r != 2 or col not in (17, 22):
            continue
        last[col] = line[line.index('"') + 1:line.rindex('"')]
    return last


def main():
    if not os.path.exists(EMU):
        sys.exit('build dosv_emu_cpp first')
    rows = {n: capture(n) for n in range(1, 31)}
    f = open('src/snap.h', 'w', encoding='utf-8', newline='\n')
    f.write('''/* What the right button would take, per command.
 *
 * Generated by tools/snap_table.py.  Two strings in the band beside the counts,
 * at columns 17 and 22.  They are there only while the pointer is over the
 * drawing -- pick an item with the pointer left on the menu and neither
 * appears -- so src/ui.c draws them then and not merely because an item is
 * picked.  They go on last: a stage writes spaces at column 17 on a black
 * background, and those reach across column 22.
 */
#ifndef JW_SNAP_H
#define JW_SNAP_H

static const char *const JW_SNAP[30][2] = {
''')
    for n in range(1, 31):
        a, b = rows[n].get(17, ''), rows[n].get(22, '')
        f.write('    { %s, %s },  /* %2d */\n'
                % (escape(a) if a else '0', escape(b) if b else '0', n))
    f.write('};\n\n#endif\n')
    f.close()
    print('wrote src/snap.h')


main()
