"""What the original writes along the top *while* a drawing command runs.

tools/menus_table.py catches the line a command puts up when it is picked.
This one catches the stages after that: what it says once the first point is
taken, and what it says when the thing is drawn.  It drives the original once
per command through tools/press.sh with all the presses, and splits what the
original wrote by *when* it wrote it -- tools/press.sh's script is a fixed
number of instructions per press, so the boundaries are known.

    python tools/stage_table.py        # writes src/stage.h

Each stage is what that press wrote, not the whole screen: the original clears
the top line as it moves on (a fill of (0,0)-(639,15) in black, seen among the
fills □ makes), so what an earlier stage left there is gone.

The numbers in those lines belong to the drawing being made (the length, the
angle, the two sides, the radius), so a run of digits is turned back into a
`%w.3f` of the same width and src/ui.c fills it in.  Nothing else is changed.
"""
import os
import re
import subprocess
import sys

B = chr(92)

# command, and the presses to make.  The points are the ones tools/presscheck.sh
# uses, so the same runs check out.
COMMANDS = [
    (3, (300, 200, 400, 200)),      # ／  a line
    (4, (250, 150, 450, 350)),      # □  a box
    (11, (300, 200, 400, 200)),     # ○  a circle
]

# tools/press.sh: 40M to start, 2M for the menu press, 24M to settle, then per
# press 3M to move, 3M held, 14M to settle.
SHOT = 66_000_000
PER_PRESS = 20_000_000
DOWN = 3_000_000

NUM = re.compile(r'( *-?\d+\.\d+)')

# The two counts and the label under them belong to the panel, not to the
# command, and src/ui.c already draws them from the drawing; what is kept from
# those two cells is only what carries a measurement.  (Columns 17 and 22 of the
# same row are the command's: they say what the right button would snap to.)
# The "please wait" flash is dropped too -- it is gone by the time the screen
# settles.
PANEL = {(1, 2), (1, 3)}
WAIT = '\x81\x96\x82\xa8\x91\xd2\x82\xbf\x89\xba\x82\xb3\x82\xa2\x81\x96'


def keep(items):
    out = []
    for k in items:
        col, row, fg, bg, s = k
        if s == WAIT:
            continue
        if (col, row) in PANEL and not NUM.search(s):
            continue
        out.append(k)
    return out


def capture(n, pts):
    """Run the original and return, for each press, what it wrote afterwards --
    the last thing per cell, because that is what is left on the screen."""
    subprocess.run(['sh', 'tools/press.sh', str(n)] + [str(v) for v in pts],
                   check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    stages = [[] for _ in range(len(pts) // 2)]
    lasts = [{} for _ in stages]
    for line in open('tmp/press/str.txt', encoding='latin-1'):
        f = line.split()
        if len(f) < 15 or f[0] != '[bp]' or line.count('"') < 2:
            continue
        t = int(f[3])
        if t < SHOT + DOWN:
            continue
        k = (t - SHOT - DOWN) // PER_PRESS
        if k >= len(stages):
            k = len(stages) - 1
        s = line[line.index('"') + 1:line.rindex('"')]
        cell = (int(f[8], 16), int(f[9], 16))
        if cell not in stages[k]:
            stages[k].append(cell)
        lasts[k][cell] = (cell[0], cell[1], int(f[10], 16), int(f[11], 16), s)
    return [keep([lasts[k][c] for c in stages[k]]) for k in range(len(stages))]


def with_formats(s):
    """Turn each run of digits into a %w.3f of the width it occupied."""
    n = 0

    def one(m):
        nonlocal n
        n += 1
        return '%%%d.3f' % len(m.group(1))

    return NUM.sub(one, s), n


def escape(s):
    out = ['"']
    for c in s:
        if c in ('"', B):
            out.append(B + c)
        elif c == '?':
            out.append(B + '?')
        elif 0x20 <= ord(c) < 0x7f:
            out.append(c)
        else:
            out.append(B + 'x%02x' % ord(c))
            out.append('" "')
    out.append('"')
    return ''.join(out).replace('"" ', '').replace(' ""', '')


def main():
    if not os.path.exists('tools/press.sh'):
        sys.exit('run this from the top of the repository')
    rows = {n: capture(n, pts) for n, pts in COMMANDS}
    f = open('src/stage.h', 'w', encoding='utf-8', newline='\n')
    f.write('''/* What a drawing command writes while it runs.
 *
 * Generated by tools/stage_table.py out of what tools/press.sh captured: the
 * emulator picks the item and presses the points, and what the original wrote
 * after each press is kept.  Do not edit by hand -- run the tool again.
 *
 * Each stage is what that press wrote.  The original clears the top line as it
 * moves on, so what the stage before left there is gone; src/ui.c does the same.
 *
 * The numbers are the drawing being made -- the length and the angle for a
 * line, the two sides for a box, the radius and the diameter for a circle -- so
 * they are here as `%%w.3f` and src/ui.c fills them in.
 */
#ifndef JW_STAGE_H
#define JW_STAGE_H

typedef struct {
    int command;                /* the menu item, or 0 to end the table */
    int stage;                  /* 1 = a point taken, 2 = the thing is drawn */
    int col, row, fg, bg;
    int numbers;                /* how many %f the text has */
    int first;                  /* which of the command's numbers the first one
                                 * is: the row under the counts carries the
                                 * second (角度, 縦, 直径), every other row the
                                 * first */
    const char *text;
} JwStage;

static const JwStage JW_STAGE[] = {
''')
    for n in sorted(rows):
        for stage, items in enumerate(rows[n], 1):
            for col, row, fg, bg, s in items:
                t, k = with_formats(s)
                f.write('    { %2d, %d, %2d, %d, %d, 0x%04x, %d, %d, %s },\n'
                        % (n, stage, col, row, fg, bg, k,
                           1 if row == 3 else 0, escape(t)))
    f.write('    { 0, 0, 0, 0, 0, 0, 0, 0, 0 },\n};\n\n#endif\n')
    f.close()
    print('wrote src/stage.h')


main()
