# -*- coding: utf-8 -*-
"""src/zukei.h -- what 図形's registration road writes, stage by stage.

    sh tools/zukei.sh                      # drive the original
    python tools/zukei_table.py > src/zukei.h

tools/zukei.sh walks 図形 ①登録 to the end and shoots after every press; this
turns the strings between two shots into a table in src/stage.h's shape.  The
stages are the presses:

    1  ①登録            図形範囲 始点マウス指示
    2  the first corner  <線･円>
    3  the other corner  (the range is fixed; 追加･除外)
    4  ①範囲 確定       ◇原図形の基準点位置
    5  the base point    ◇ 図形選択 |①選択確定 |②ドライブ …
    6  ①選択確定        図形 登録 ◆図形名入力
    7  the name, [Enter] 書き込みます |① 実 行(L)|② 再選択(R)|
    8  ① 実 行          back to 図形's own line

Only row 1 is kept: the rest of what those presses write is the file screen's
own furniture, which src/ui.c draws from the drawing rather than replaying.
"""
import io
import os
import re
import sys

sys.stdout.reconfigure(encoding='utf-8', newline='\n')

LOG = os.environ.get('ZUKEILOG', 'tmp/zukei/raw.txt')
WAIT = b'\x81\x96\x82\xa8\x91\xd2\x82\xbf\x89\xba\x82\xb3\x82\xa2\x81\x96'


def literal(raw, indent='      ', width=58):
    chunks, cur, cur_hex = [], '', False
    for ch in raw:
        hexed = not (0x20 <= ch < 0x7f) or ch in (0x22, 0x5c)
        if cur and hexed != cur_hex:
            chunks.append('"%s"' % cur)
            cur = ''
        cur += '\\x%02x' % ch if hexed else chr(ch)
        cur_hex = hexed
    if cur:
        chunks.append('"%s"' % cur)
    if not chunks:
        return '""'
    lines, line = [], ''
    for c in chunks:
        if line and len(line) + 1 + len(c) > width:
            lines.append(line)
            line = c
        else:
            line = line + ' ' + c if line else c
    if line:
        lines.append(line)
    return (' \\\n' + indent).join(lines)


held, stages = [], {}
for line in open(LOG, encoding='latin-1'):
    m = re.search(r'\[shot\] .*?s(\d+)\.raw', line)
    if m:
        stages[int(m.group(1))] = held
        held = []
        continue
    if '[bp]' not in line or line.count('"') < 2:
        continue
    f = line.split()
    if len(f) < 15:
        continue
    try:
        col, row = int(f[8], 16), int(f[9], 16)
        fg, bg = int(f[10], 16), int(f[11], 16)
    except ValueError:
        continue
    text = line[line.index('"'):].rstrip('\n')
    held.append((col, row, fg, bg,
                 text[text.index('"') + 1:text.rindex('"')].encode('latin-1')))

print('''/* src/zukei.h -- 図形's registration road, as the original writes it.
 *
 * Generated by tools/zukei_table.py out of what tools/zukei.sh captured.
 * Do not edit by hand -- run the two again.
 *
 * `orig/JW_CADV.HLP` (図 形 その1/4) says what the road is; this is what the
 * original puts on the top line at each step of it.
 */
#ifndef JW_ZUKEI_H
#define JW_ZUKEI_H

/* The steps of 図形 ①登録, which are the presses tools/zukei.sh makes.
 * JwCmd.zukei holds one of these once the item has been pressed. */
#define JW_ZUKEI_RANGE  1       /* 図形範囲 始点マウス指示 */
#define JW_ZUKEI_BASE   3       /* ◇原図形の基準点位置 */
#define JW_ZUKEI_PICK   5       /* ◇ 図形選択 |①選択確定 |… */
#define JW_ZUKEI_NAME   6       /* 図形 登録 ◆図形名入力 */
#define JW_ZUKEI_WRITE  7       /* 書き込みます |① 実 行(L)|② 再選択(R)| */
#define JW_ZUKEI_DONE   8

typedef struct {
    int stage;                  /* which press, 1 to 8; 0 ends the table */
    int col, fg, bg;
    const char *text;
} JwZukei;

static const JwZukei JW_ZUKEI[] = {''')

n = 0
for stage in sorted(stages):
    if stage == 0:
        continue
    rows = [r for r in stages[stage] if r[1] == 1 and r[4] != WAIT]
    if not rows:
        continue
    print('    /* press %d */' % stage)
    for col, row, fg, bg, raw in rows:
        print('    { %d, %2d, %d, 0x%04X,\n      %s },'
              % (stage, col, fg, bg, literal(raw)))
        n += 1
print('''    { 0, 0, 0, 0, 0 }
};

#endif''')
sys.stderr.write('%d writes\n' % n)
