/* src/item.h -- what a press on a cell of a command's top row writes.
 *
 * Generated by tools/item_table.py out of what tools/branchstr.sh captured.
 * Do not edit by hand -- run the tool again.
 *
 * src/prompt.h is the line the *menu* item comes up with; this is the writes
 * the cells on that line make when they are pressed.  They are a difference,
 * not a whole line: the original writes over part of the row and leaves the
 * rest, so src/ui.c replays them **on top of** the prompt.
 *
 * **This is the line, not the behaviour.**  It covers the cells no command
 * has been built for yet, so that the screen is the original's while the work
 * goes on; as each one grows its own code in src/cmd.c it claims the press
 * and drops out of here.
 */
#ifndef JW_ITEM_H
#define JW_ITEM_H

typedef struct {
    int command;                /* the menu item, 1 to 30, or 0 to end */
    int item;                   /* which cell of the top row was pressed */
    int right;                  /* 1 if that was the right button */
    int col, row, fg, bg;
    const char *text;
} JwItem;

static const JwItem JW_ITEM[] = {
    /* branch 2: menu 1 item 1 left */
    {  1,  1, 0,  1, 1, 7, 0x0000,
      "[ESC]" },
    {  1,  1, 0,  6, 1, 7, 0x0000,
      "\x81" "Q" },
    {  1,  1, 0,  8, 1, 7, 0x0000,
      "\x95\xa1\x8e\xca\x94\xcd\x88\xcd" "  " \
      "\x92\xc7\x89\xc1\xa5\x8f\x9c\x8a" "O" "\x83" "f" "\x81" \
      "[" "\x83" "^" "\x8e" "w" "\x8e\xa6" "   " },
    {  1,  1, 0, 50, 1, 7, 0x0000,
      "\x95\xb6\x8e\x9a" "(R)" },
    {  1,  1, 0, 57, 1, 7, 0x0000,
      " [F1" "\x81" "`F10] " },
    {  1,  1, 0, 68, 1, 7, 0x0000,
      "|" "\x87" "@" "\x94\xcd\x88\xcd" " " "\x8a" "m" \
      "\x92\xe8" "|" },
    /* branch 3: menu 1 item 1 right */
    {  1,  1, 1,  1, 1, 7, 0x0000,
      "[ESC]" },
    {  1,  1, 1,  6, 1, 7, 0x0000,
      "\x81" "Q" },
    {  1,  1, 1,  8, 1, 7, 0x0000,
      "\x95\xa1\x8e\xca\x94\xcd\x88\xcd" "  " \
      "\x92\xc7\x89\xc1\xa5\x8f\x9c\x8a" "O" "\x83" "f" "\x81" \
      "[" "\x83" "^" "\x8e" "w" "\x8e\xa6" "   " },
    {  1,  1, 1, 40, 1, 7, 0x0000,
      "\x90\xfc\x81" "E" "\x89" "~(L) " },
    {  1,  1, 1, 50, 1, 7, 0x0000,
      "\x95\xb6\x8e\x9a" "(R)" },
    {  1,  1, 1, 68, 1, 7, 0x0000,
      "|" "\x87" "@" "\x94\xcd\x88\xcd" " " "\x8a" "m" \
      "\x92\xe8" "|" },
    /* branch 29: menu 4 item 3 left */
    {  4,  3, 0,  1, 1, 7, 0x0000,
      "[ESC]" },
    {  4,  3, 0,  8, 1, 7, 0x0000,
      "\x8a\xee\x8f\x80\x90\xfc\x81" "@" "\x83" "}" "\x83" "E" \
      "\x83" "X" "\x8e" "w" "\x8e\xa6" " |" "\x87" "@" "\x8e" \
      "w" "\x92\xe8\x89\xf0\x8f\x9c" "|" },
    /* branch 30: menu 4 item 3 right */
    {  4,  3, 1,  1, 1, 7, 0x0000,
      "[ESC]" },
    {  4,  3, 1,  8, 1, 7, 0x0000,
      "\x8a\xee\x8f\x80\x90\xfc\x81" "@" "\x83" "}" "\x83" "E" \
      "\x83" "X" "\x8e" "w" "\x8e\xa6" " |" "\x87" "@" "\x8e" \
      "w" "\x92\xe8\x89\xf0\x8f\x9c" "|" },
    /* branch 36 (menu 5 item 2 left): the press wrote nothing */
    /* branch 37 (menu 5 item 2 right): the press wrote nothing */
    /* branch 41: menu 8 item 1 left */
    {  8,  1, 0,  6, 1, 7, 0x0000,
      "\x81" "E" },
    /* branch 42: menu 8 item 1 right */
    {  8,  1, 1,  6, 1, 7, 0x0000,
      "\x81" "E" },
    {  8,  1, 1,  8, 1, 7, 0x0000,
      "\x91\xce\x8f\xdb\x90\xfc" "(" "\x82" "`)" "\x83" "}" \
      "\x83" "E" "\x83" "X" "\x8e" "w" "\x8e\xa6" " |" "\x87" \
      "@" "\x81" "y" "\x82" "k" "\x96\xca\x81" "z|" "\x87" \
      "A(A),(B)" "\x95\xd3" "= 30.000, 30.000|" },
    /* branch 43: menu 8 item 2 left */
    {  8,  2, 0,  1, 1, 7, 0x0000,
      "[ESC].(A),(B)" "\x95\xd3" " =" },
    {  8,  2, 0, 38, 1, 7, 0x0000,
      "\x91" "O" "\x89\xf1\x82\xc6\x93\xaf\x82\xb6" " " \
      "\xcf\xb3\xbd" "(R) " },
    {  8,  2, 0, 56, 1, 7, 0x0000,
      "[    30.000" },
    {  8,  2, 0, 67, 1, 7, 0x0000,
      ",    30.000" },
    {  8,  2, 0, 80, 1, 7, 0x0000,
      "]" },
    {  8,  2, 0, 19, 1, 7, 0x0000,
      "        " },
    /* branch 44: menu 8 item 2 right */
    {  8,  2, 1,  1, 1, 7, 0x0000,
      "[ESC].(A),(B)" "\x95\xd3" " =" },
    {  8,  2, 1, 38, 1, 7, 0x0000,
      "\x91" "O" "\x89\xf1\x82\xc6\x93\xaf\x82\xb6" " " \
      "\xcf\xb3\xbd" "(R) " },
    {  8,  2, 1, 56, 1, 7, 0x0000,
      "[    30.000" },
    {  8,  2, 1, 67, 1, 7, 0x0000,
      ",    30.000" },
    {  8,  2, 1, 78, 1, 7, 0x0000,
      "mm" },
    {  8,  2, 1, 80, 1, 7, 0x0000,
      "]" },
    /* branch 45: menu 8 item 3 left */
    {  8,  3, 0,  1, 1, 7, 0x0000,
      "[ESC].(A),(B)" "\x95\xd3" " =" },
    {  8,  3, 0, 38, 1, 7, 0x0000,
      "\x91" "O" "\x89\xf1\x82\xc6\x93\xaf\x82\xb6" " " \
      "\xcf\xb3\xbd" "(R) " },
    {  8,  3, 0, 56, 1, 7, 0x0000,
      "[    30.000" },
    {  8,  3, 0, 67, 1, 7, 0x0000,
      ",    30.000" },
    {  8,  3, 0, 78, 1, 7, 0x0000,
      "mm" },
    {  8,  3, 0, 80, 1, 7, 0x0000,
      "]" },
    {  8,  3, 0, 19, 1, 7, 0x0000,
      "        " },
    /* branch 46: menu 8 item 3 right */
    {  8,  3, 1,  1, 1, 7, 0x0000,
      "[ESC].(A),(B)" "\x95\xd3" " =" },
    {  8,  3, 1, 56, 1, 7, 0x0000,
      "[    30.000" },
    {  8,  3, 1, 67, 1, 7, 0x0000,
      ",    30.000" },
    {  8,  3, 1, 78, 1, 7, 0x0000,
      "mm" },
    {  8,  3, 1, 80, 1, 7, 0x0000,
      "]" },
    {  8,  3, 1, 19, 1, 7, 0x0000,
      "        " },
    /* branch 47 (menu 8 item 4 left): the press wrote nothing */
    /* branch 48 (menu 8 item 4 right): the press wrote nothing */
    /* branch 49 (menu 8 item 5 left): the press wrote nothing */
    /* branch 50 (menu 8 item 5 right): the press wrote nothing */
    /* branch 54 (menu 9 item 2 left): the press wrote nothing */
    /* branch 55 (menu 9 item 2 right): the press wrote nothing */
    /* branch 60: menu 11 item 2 left */
    { 11,  2, 0,  6, 1, 7, 0x0000,
      "\x81" "E" },
    { 11,  2, 0,  8, 1, 7, 0x0000,
      "\x81\x9b" " " "\x91\xc8\x89" "~" "\x92\x86\x90" "S" \
      "\x93" "_ " "\x83" "}" "\x83" "E" "\x83" "X" "\x8e" "w" \
      "\x8e\xa6" " (L)free (R)Read " },
    { 11,  2, 0, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 61: menu 11 item 2 right */
    { 11,  2, 1,  6, 1, 7, 0x0000,
      "\x81" "E" },
    { 11,  2, 1,  8, 1, 7, 0x0000,
      "\x81\x9b" " " "\x91\xc8\x89" "~" "\x92\x86\x90" "S" \
      "\x93" "_ " "\x83" "}" "\x83" "E" "\x83" "X" "\x8e" "w" \
      "\x8e\xa6" " (L)free (R)Read " },
    { 11,  2, 1, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 65: menu 12 item 1 left */
    { 12,  1, 0,  8, 1, 7, 0x0000,
      "\x81\x9e" " " "\x8e" "n" "\x93" "_" "\x8e" "w" "\x8e\xa6" \
      " (L)free (R)Read " },
    { 12,  1, 0, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 66: menu 12 item 1 right */
    { 12,  1, 1,  8, 1, 7, 0x0000,
      "\x81\x9e" " " "\x8e" "n" "\x93" "_" "\x8e" "w" "\x8e\xa6" \
      " (L)free (R)Read " },
    { 12,  1, 1, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 67: menu 12 item 2 left */
    { 12,  2, 0, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 68: menu 12 item 2 right */
    { 12,  2, 1,  8, 1, 7, 0x0000,
      "\x81\x9e" " " "\x8e" "n" "\x93" "_" "\x8e" "w" "\x8e\xa6" \
      " (L)free (R)Read " },
    /* branch 69: menu 12 item 3 left */
    { 12,  3, 0,  8, 1, 7, 0x0000,
      "\x81\x9e" " " "\x8e" "n" "\x93" "_" "\x8e" "w" "\x8e\xa6" \
      " (L)free (R)Read " },
    { 12,  3, 0, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 70: menu 12 item 3 right */
    { 12,  3, 1,  8, 1, 7, 0x0000,
      "\x81\x9e" " " "\x8e" "n" "\x93" "_" "\x8e" "w" "\x8e\xa6" \
      " (L)free (R)Read " },
    { 12,  3, 1, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 74: menu 13 item 1 left */
    { 13,  1, 0,  1, 2, 0, 0x0000,
      "     30|     13 " },
    { 13,  1, 0,  1, 3, 0, 0x0000,
      " " "\x90\xfc" "  " "\x90\x94" "|" "\x89" "~" \
      "\xa5\x95\xb6\x90\x94" },
    { 13,  1, 0,  1, 2, 0, 0x0000,
      " " "\xcd\xdf\xdd" "2 " "\x8a\xee\x93" "_ " \
      "\x8d\xb6\x89\xba" " " },
    { 13,  1, 0,  1, 3, 0, 0x0000,
      " " "\x89\xa1" " 3.0 " "\x8f" "c 3.0 " },
    { 13,  1, 0,  6, 1, 7, 0x0000,
      "\x81" "E" },
    { 13,  1, 0, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 75: menu 13 item 1 right */
    { 13,  1, 1,  1, 2, 0, 0x0000,
      "     30|     13 " },
    { 13,  1, 1,  1, 3, 0, 0x0000,
      " " "\x90\xfc" "  " "\x90\x94" "|" "\x89" "~" \
      "\xa5\x95\xb6\x90\x94" },
    { 13,  1, 1,  1, 2, 0, 0x0000,
      " " "\xcd\xdf\xdd" "2 " "\x8a\xee\x93" "_ " \
      "\x8d\xb6\x89\xba" " " },
    { 13,  1, 1,  1, 3, 0, 0x0000,
      " " "\x89\xa1" " 3.0 " "\x8f" "c 3.0 " },
    { 13,  1, 1,  6, 1, 7, 0x0000,
      "\x81" "E" },
    { 13,  1, 1,  8, 1, 7, 0x0000,
      "\x95\xb6\x8e\x9a\x8e\xed\x97\xde" "[F3]  " "\x8a\xee\x93" \
      "_" "\x8e" "w" "\x8e\xa6" "(L)free(R)Read|" "\x87" "@" \
      "\x8a\xee\x93" "_" "\x95\xcf" "|" "\x87" "A" "\x8d" "s" \
      "\x98" "A" "\x91\xb1" "|" "\x87" "B" "\x97\xf1\x98" "A" \
      "\x91\xb1" "|" },
    { 13,  1, 1, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 76: menu 13 item 2 left */
    { 13,  2, 0,  1, 2, 0, 0x0000,
      "     30|     13 " },
    { 13,  2, 0,  1, 3, 0, 0x0000,
      " " "\x90\xfc" "  " "\x90\x94" "|" "\x89" "~" \
      "\xa5\x95\xb6\x90\x94" },
    { 13,  2, 0,  1, 2, 0, 0x0000,
      " " "\xcd\xdf\xdd" "2 " "\x8a\xee\x93" "_ " \
      "\x8d\xb6\x89\xba" " " },
    { 13,  2, 0,  1, 3, 0, 0x0000,
      " " "\x89\xa1" " 3.0 " "\x8f" "c 3.0 " },
    { 13,  2, 0,  6, 1, 7, 0x0000,
      "\x81" "E" },
    { 13,  2, 0,  8, 1, 7, 0x0000,
      "\x95\xb6\x8e\x9a\x8e\xed\x97\xde" "[F3]  " "\x8a\xee\x93" \
      "_" "\x8e" "w" "\x8e\xa6" "(L)free(R)Read|" "\x87" "@" \
      "\x8a\xee\x93" "_" "\x95\xcf" "|" "\x87" "A" "\x8d" "s" \
      "\x98" "A" "\x91\xb1" "|" "\x87" "B" "\x97\xf1\x98" "A" \
      "\x91\xb1" "|" },
    { 13,  2, 0, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 77: menu 13 item 2 right */
    { 13,  2, 1,  1, 2, 0, 0x0000,
      "     30|     13 " },
    { 13,  2, 1,  1, 2, 0, 0x0000,
      " " "\xcd\xdf\xdd" "2 " "\x8a\xee\x93" "_ " \
      "\x8d\xb6\x89\xba" " " },
    { 13,  2, 1,  1, 3, 0, 0x0000,
      " " "\x89\xa1" " 3.0 " "\x8f" "c 3.0 " },
    { 13,  2, 1,  6, 1, 7, 0x0000,
      "\x81" "E" },
    { 13,  2, 1,  8, 1, 7, 0x0000,
      "\x95\xb6\x8e\x9a\x8e\xed\x97\xde" "[F3]  " "\x8a\xee\x93" \
      "_" "\x8e" "w" "\x8e\xa6" "(L)free(R)Read|" "\x87" "@" \
      "\x8a\xee\x93" "_" "\x95\xcf" "|" "\x87" "A" "\x8d" "s" \
      "\x98" "A" "\x91\xb1" "|" "\x87" "B" "\x97\xf1\x98" "A" \
      "\x91\xb1" "|" },
    { 13,  2, 1, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 84: menu 13 item 6 left */
    { 13,  6, 0,  1, 2, 0, 0x0000,
      "     30|     13 " },
    { 13,  6, 0,  1, 3, 0, 0x0000,
      " " "\x90\xfc" "  " "\x90\x94" "|" "\x89" "~" \
      "\xa5\x95\xb6\x90\x94" },
    { 13,  6, 0,  1, 3, 0, 0x0000,
      " " "\x89\xa1" " 3.0 " "\x8f" "c 3.0 " },
    { 13,  6, 0,  6, 1, 7, 0x0000,
      "\x81" "E" },
    { 13,  6, 0,  8, 1, 7, 0x0000,
      "\x95\xb6\x8e\x9a\x8e\xed\x97\xde" "[F3] |" "\x87" "@" \
      "\x90\x85\x95\xbd" "(L,R)|" "\x87" "A" "\x90\x82\x92\xbc" \
      "|" "\x87" "B" "\x8a" "p" "\x93" "x" "\x8e" "w" "\x92\xe8" \
      "|" "\x87" "C" "\x90\xdd\x92\xe8" "|" "\x87" "D" \
      "\x95\xb6" "[" "\x8f\x91" "/" "\x93\xc7" "]|" "\x87" "E(" \
      "\x8f" "c)" "\x8e\x9a" "|" },
    /* branch 95: menu 14 item 4 left */
    { 14,  4, 0,  1, 1, 7, 0x0000,
      "[ESC]" },
    { 14,  4, 0,  6, 1, 7, 0x0000,
      "\x81" "E" },
    { 14,  4, 0,  8, 1, 7, 0x0000,
      "|" "\x87" "@" "\x89" "~" "\x8c" "a(L) |" "\x87" "A" \
      "\x89" "~" "\x8e\xfc" "(R) |" "\x87" "B" "\x8a" "p" "\x93" \
      "x |" },
    /* branch 96: menu 14 item 4 right */
    { 14,  4, 1,  1, 1, 7, 0x0000,
      "[ESC]" },
    { 14,  4, 1,  6, 1, 7, 0x0000,
      "\x81" "E" },
    { 14,  4, 1,  8, 1, 7, 0x0000,
      "|" "\x87" "@" "\x89" "~" "\x8c" "a(L) |" "\x87" "A" \
      "\x89" "~" "\x8e\xfc" "(R) |" "\x87" "B" "\x8a" "p" "\x93" \
      "x |" },
    /* branch 99: menu 14 item 6 left */
    { 14,  6, 0,  8, 1, 7, 0x0000,
      "\x93" "_(No.1) " "\x81\x9c" " " "\x93" "_" "\x8d\xec\x90" \
      "} " "\xcf\xb3\xbd" "(L)    " "\x93" "_" \
      "\x8e\xed\x95\xcf\x8d" "X " "\xcf\xb3\xbd" "(R)         " \
      "\x93" "_" "\x90\x94" " 16" },
    { 14,  6, 0, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 100: menu 14 item 6 right */
    { 14,  6, 1,  8, 1, 7, 0x0000,
      "\x93" "_(No.1) " "\x81\x9c" " " "\x93" "_" "\x8d\xec\x90" \
      "} " "\xcf\xb3\xbd" "(L)    " "\x93" "_" \
      "\x8e\xed\x95\xcf\x8d" "X " "\xcf\xb3\xbd" "(R)         " \
      "\x93" "_" "\x90\x94" " 16" },
    { 14,  6, 1, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 101: menu 14 item 7 left */
    { 14,  7, 0,  8, 1, 7, 0x0000,
      "\x81\x83" "-- " \
      "\x96\xee\x88\xf3\x82\xf0\x8f\x91\x82\xad\x81" "m" \
      "\x90\xfc\xa5\x8c\xca\x81" "n " "\x83" "}" "\x83" "E" \
      "\x83" "X" "\x8e" "w" "\x8e\xa6" " " },
    { 14,  7, 0, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 102: menu 14 item 7 right */
    { 14,  7, 1,  8, 1, 7, 0x0000,
      "\x81\x83" "-- " \
      "\x96\xee\x88\xf3\x82\xf0\x8f\x91\x82\xad\x81" "m" \
      "\x90\xfc\xa5\x8c\xca\x81" "n " "\x83" "}" "\x83" "E" \
      "\x83" "X" "\x8e" "w" "\x8e\xa6" " " },
    { 14,  7, 1, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 127: menu 16 item 1 left */
    { 16,  1, 0,  1, 1, 7, 0x0000,
      "[ESC]" },
    { 16,  1, 0,  8, 1, 7, 0x0000,
      "\x88\xda\x93\xae\x94\xcd\x88\xcd" "  " \
      "\x92\xc7\x89\xc1\xa5\x8f\x9c\x8a" "O" "\x83" "f" "\x81" \
      "[" "\x83" "^" "\x8e" "w" "\x8e\xa6" "   " },
    { 16,  1, 0, 40, 1, 7, 0x0000,
      "\x90\xfc\x81" "E" "\x89" "~(L) " },
    { 16,  1, 0, 50, 1, 7, 0x0000,
      "\x95\xb6\x8e\x9a" "(R)" },
    { 16,  1, 0, 57, 1, 7, 0x0000,
      " [F1" "\x81" "`F10] " },
    { 16,  1, 0, 68, 1, 7, 0x0000,
      "|" "\x87" "@" "\x94\xcd\x88\xcd" " " "\x8a" "m" \
      "\x92\xe8" "|" },
    /* branch 128: menu 16 item 1 right */
    { 16,  1, 1,  1, 1, 7, 0x0000,
      "[ESC]" },
    { 16,  1, 1,  6, 1, 7, 0x0000,
      "\x81" "Q" },
    { 16,  1, 1, 40, 1, 7, 0x0000,
      "\x90\xfc\x81" "E" "\x89" "~(L) " },
    { 16,  1, 1, 50, 1, 7, 0x0000,
      "\x95\xb6\x8e\x9a" "(R)" },
    { 16,  1, 1, 57, 1, 7, 0x0000,
      " [F1" "\x81" "`F10] " },
    { 16,  1, 1, 68, 1, 7, 0x0000,
      "|" "\x87" "@" "\x94\xcd\x88\xcd" " " "\x8a" "m" \
      "\x92\xe8" "|" },
    /* branch 130 (menu 17 item 1 left): the press wrote nothing */
    /* branch 131 (menu 17 item 1 right): the press wrote nothing */
    /* branch 132 (menu 17 item 2 left): the press wrote nothing */
    /* branch 133 (menu 17 item 2 right): the press wrote nothing */
    /* branch 134 (menu 17 item 3 left): the press wrote nothing */
    /* branch 135 (menu 17 item 3 right): the press wrote nothing */
    /* branch 136 (menu 17 item 4 left): the press wrote nothing */
    /* branch 137 (menu 17 item 4 right): the press wrote nothing */
    /* branch 138 (menu 17 item 5 left): the press wrote nothing */
    /* branch 139 (menu 17 item 5 right): the press wrote nothing */
    /* branch 142: menu 19 item 1 left */
    { 19,  1, 0,  8, 1, 7, 0x0000,
      "\x82" "Q" "\x93" "_" \
      "\x82\xa9\x82\xe7\x82\xcc\x8b\x97\x97\xa3" " " "\x82" "`" \
      "\x93" "_" "\x83" "}" "\x83" "E" "\x83" "X" "\x8e" "w" \
      "\x8e\xa6" " (L)free (R)Read " },
    { 19,  1, 0, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 143: menu 19 item 1 right */
    { 19,  1, 1, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 146: menu 19 item 3 left */
    { 19,  3, 0,  8, 1, 7, 0x0000,
      "\x8c\xb4\x93" "_" "\x83" "}" "\x83" "E" "\x83" "X" "\x8e" \
      "w" "\x8e\xa6" " (L)free (R)Read |" "\x87" "@" \
      "\x8c\xb4\x93" "_" "\x8d\xb6\x89\xba" "|" "\x87" "A" \
      "\x81" "yXY" "\x8d\xc0\x95" "W" "\x81" "z" \
      "\x8b\xc9\x8d\xc0\x95" "W|" },
    { 19,  3, 0, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 147: menu 19 item 3 right */
    { 19,  3, 1,  8, 1, 7, 0x0000,
      "\x8c\xb4\x93" "_" "\x83" "}" "\x83" "E" "\x83" "X" "\x8e" \
      "w" "\x8e\xa6" " (L)free (R)Read |" "\x87" "@" \
      "\x8c\xb4\x93" "_" "\x8d\xb6\x89\xba" "|" "\x87" "A" \
      "\x81" "yXY" "\x8d\xc0\x95" "W" "\x81" "z" \
      "\x8b\xc9\x8d\xc0\x95" "W|" },
    { 19,  3, 1, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 154: menu 21 item 1 left */
    { 21,  1, 0,  8, 1, 7, 0x0000,
      "\x81\x9e\x82" "Q" "\x93" "_" \
      "\x8a\xd4\x95\xaa\x8a\x84\x93" "_ " "\x8e" "n" "\x93" "_" \
      "\x8e" "w" "\x8e\xa6" " (L)free (R)Read |" "\x87" "@" \
      "\x81" "y" "\x89\xbc\x93" "_" "\x81" "z| " "\x8e" "c 100" },
    { 21,  1, 0, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 155: menu 21 item 1 right */
    { 21,  1, 1,  8, 1, 7, 0x0000,
      "\x81\x9e\x82" "Q" "\x93" "_" \
      "\x8a\xd4\x95\xaa\x8a\x84\x93" "_ " "\x8e" "n" "\x93" "_" \
      "\x8e" "w" "\x8e\xa6" " (L)free (R)Read |" "\x87" "@" \
      "\x81" "y" "\x89\xbc\x93" "_" "\x81" "z| " "\x8e" "c 100" },
    { 21,  1, 1, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 156: menu 21 item 2 left */
    { 21,  2, 0,  8, 1, 7, 0x0000,
      "\x81\x9e\x89" "~" "\x95\xaa\x8a\x84\x93" "_" "\x81" "i" \
      "\x8d\xb6\x89\xf4\x82\xe8\x81" "j  " "\x89" "~" \
      "\x8c\xca\x83" "}" "\x83" "E" "\x83" "X" "\x8e" "w" \
      "\x8e\xa6" " |" "\x87" "@" "\x81" "y" "\x89\xbc\x93" "_" \
      "\x81" "z| " "\x8e" "c 100" },
    { 21,  2, 0, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 157: menu 21 item 2 right */
    { 21,  2, 1,  8, 1, 7, 0x0000,
      "\x81\x9e\x89" "~" "\x95\xaa\x8a\x84\x93" "_" "\x81" "i" \
      "\x8d\xb6\x89\xf4\x82\xe8\x81" "j  " "\x89" "~" \
      "\x8c\xca\x83" "}" "\x83" "E" "\x83" "X" "\x8e" "w" \
      "\x8e\xa6" " |" "\x87" "@" "\x81" "y" "\x89\xbc\x93" "_" \
      "\x81" "z| " "\x8e" "c 100" },
    { 21,  2, 1, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 158: menu 21 item 3 left */
    { 21,  3, 0, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 159: menu 21 item 3 right */
    { 21,  3, 1,  8, 1, 7, 0x0000,
      "\x81\x9e\x91\xc8\x89" "~" "\x95\xaa\x8a\x84\x93" "_" \
      "\x81" "i" "\x8d\xb6\x89\xf4\x82\xe8\x81" "j  " "\x89" "~" \
      "\x8c\xca\x83" "}" "\x83" "E" "\x83" "X" "\x8e" "w" \
      "\x8e\xa6" " |" "\x87" "@" "\x81" "y" "\x89\xbc\x93" "_" \
      "\x81" "z| " "\x8e" "c 100" },
    /* branch 160: menu 21 item 4 left */
    { 21,  4, 0,  8, 1, 7, 0x0000,
      "\x90\xfc\x81" "i" "\x82" "`" "\x81" "j" "\x83" "}" "\x83" \
      "E" "\x83" "X" "\x8e" "w" "\x8e\xa6" " (" "\x82" "Q" \
      "\x90\xfc\x8a\xd4\x82\xcc\x93\x99\x95\xaa\x8a\x84\x90\xfc" \
      ")" },
    { 21,  4, 0, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 161: menu 21 item 4 right */
    { 21,  4, 1,  8, 1, 7, 0x0000,
      "\x90\xfc\x81" "i" "\x82" "`" "\x81" "j" "\x83" "}" "\x83" \
      "E" "\x83" "X" "\x8e" "w" "\x8e\xa6" " (" "\x82" "Q" \
      "\x90\xfc\x8a\xd4\x82\xcc\x93\x99\x95\xaa\x8a\x84\x90\xfc" \
      ")" },
    { 21,  4, 1, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 167: menu 22 item 2 left */
    { 22,  2, 0,  8, 1, 7, 0x0000,
      "\x8b\x97\x97\xa3" "  " "\x8e" "n" "\x93" "_" "\x8e" "w" \
      "\x8e\xa6" " (L)free (R)Read |" "\x87" "@" "\x81" "y" \
      "\x92\xbc\x90" "i" "\x8b\x97\x97\xa3\x81" "z|" },
    { 22,  2, 0, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 168: menu 22 item 2 right */
    { 22,  2, 1,  8, 1, 7, 0x0000,
      "\x8b\x97\x97\xa3" "  " "\x8e" "n" "\x93" "_" "\x8e" "w" \
      "\x8e\xa6" " (L)free (R)Read |" "\x87" "@" "\x81" "y" \
      "\x92\xbc\x90" "i" "\x8b\x97\x97\xa3\x81" "z|" },
    { 22,  2, 1, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 169: menu 22 item 3 left */
    { 22,  3, 0,  8, 1, 7, 0x0000,
      "\x81\x9e\x8c\xf0\x93" "_" "\x81" "@ " \
      "\x91\xce\x8f\xdb\x90\xfc\x81" "i" "\x82" "`" "\x81" "j" \
      "\x83" "}" "\x83" "E" "\x83" "X" "\x8e" "w" "\x8e\xa6" " " },
    { 22,  3, 0, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 170: menu 22 item 3 right */
    { 22,  3, 1,  8, 1, 7, 0x0000,
      "\x81\x9e\x8c\xf0\x93" "_" "\x81" "@ " \
      "\x91\xce\x8f\xdb\x90\xfc\x81" "i" "\x82" "`" "\x81" "j" \
      "\x83" "}" "\x83" "E" "\x83" "X" "\x8e" "w" "\x8e\xa6" " " },
    { 22,  3, 1, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 171 (menu 22 item 4 left): the press wrote nothing */
    /* branch 172: menu 22 item 4 right */
    { 22,  4, 1, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 173: menu 22 item 5 left */
    { 22,  5, 0,  8, 1, 7, 0x0000,
      "\x89\xbc\x93" "_" "\x8d\xed\x8f\x9c" "  " "\x89\xbc\x93" \
      "_" "\x83" "}" "\x83" "E" "\x83" "X" "\x8e" "w" "\x8e\xa6" \
      " |" "\x87" "@" "\x91" "S" "\x89\xbc\x93" "_" \
      "\x8d\xed\x8f\x9c" " |  " \
      "\x8c\xbb\x8d\xdd\x82\xcc\x90\x94" " [0]" },
    /* branch 174: menu 22 item 5 right */
    { 22,  5, 1,  8, 1, 7, 0x0000,
      "\x89\xbc\x93" "_" "\x8d\xed\x8f\x9c" "  " "\x89\xbc\x93" \
      "_" "\x83" "}" "\x83" "E" "\x83" "X" "\x8e" "w" "\x8e\xa6" \
      " |" "\x87" "@" "\x91" "S" "\x89\xbc\x93" "_" \
      "\x8d\xed\x8f\x9c" " |  " \
      "\x8c\xbb\x8d\xdd\x82\xcc\x90\x94" " [0]" },
    { 22,  5, 1, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 176: menu 23 item 1 left */
    { 23,  1, 0,  8, 1, 7, 0x0000,
      "\xbb\xb2\xdd\x8b\xc8\x90\xfc" "  " \
      "\x81\x9e\x8a\xee\x8f\x80\x90\xfc\x81" "@" "\x83" "}" \
      "\x83" "E" "\x83" "X" "\x8e" "w" "\x8e\xa6" " " },
    { 23,  1, 0, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 177: menu 23 item 1 right */
    { 23,  1, 1,  8, 1, 7, 0x0000,
      "\xbb\xb2\xdd\x8b\xc8\x90\xfc" "  " \
      "\x81\x9e\x8a\xee\x8f\x80\x90\xfc\x81" "@" "\x83" "}" \
      "\x83" "E" "\x83" "X" "\x8e" "w" "\x8e\xa6" " " },
    { 23,  1, 1, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 178: menu 23 item 2 left */
    { 23,  2, 0,  8, 1, 7, 0x0000,
      "\x82" "Q" "\x8e\x9f\x8b\xc8\x90\xfc" "  " \
      "\x81\x9e\x8a\xee\x8f\x80\x90\xfc\x81" "@" "\x83" "}" \
      "\x83" "E" "\x83" "X" "\x8e" "w" "\x8e\xa6" " " },
    { 23,  2, 0, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 179: menu 23 item 2 right */
    { 23,  2, 1,  8, 1, 7, 0x0000,
      "\x82" "Q" "\x8e\x9f\x8b\xc8\x90\xfc" "  " \
      "\x81\x9e\x8a\xee\x8f\x80\x90\xfc\x81" "@" "\x83" "}" \
      "\x83" "E" "\x83" "X" "\x8e" "w" "\x8e\xa6" " " },
    { 23,  2, 1, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 180: menu 23 item 3 left */
    { 23,  3, 0,  8, 1, 7, 0x0000,
      "\xbd\xcc\xdf\xd7\xb2\xdd\x8b\xc8\x90\xfc\x81\x9e" "     " \
      "\x8e" "n" "\x93" "_    " "\x8e" "w" "\x8e\xa6" \
      "(L)free (R)Read  " "\x93" "_" "\x8e" "c" "\x90\x94" " 50" },
    { 23,  3, 0, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 181: menu 23 item 3 right */
    { 23,  3, 1,  8, 1, 7, 0x0000,
      "\xbd\xcc\xdf\xd7\xb2\xdd\x8b\xc8\x90\xfc\x81\x9e" "     " \
      "\x8e" "n" "\x93" "_    " "\x8e" "w" "\x8e\xa6" \
      "(L)free (R)Read  " "\x93" "_" "\x8e" "c" "\x90\x94" " 50" },
    { 23,  3, 1, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 182: menu 23 item 4 left */
    { 23,  4, 0, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 183: menu 23 item 4 right */
    { 23,  4, 1,  8, 1, 7, 0x0000,
      "\xcd\xde\xbc\xde\xaa\x8b\xc8\x90\xfc\x81\x9e" "     " \
      "\x8e" "n" "\x93" "_    " "\x8e" "w" "\x8e\xa6" \
      "(L)free (R)Read  " "\x93" "_" "\x8e" "c" "\x90\x94" " 50" },
    /* branch 184: menu 23 item 5 left */
    { 23,  5, 0,  1, 2, 0, 0x0000,
      "     30|     13 " },
    { 23,  5, 0,  1, 3, 0, 0x0000,
      " " "\x90\xfc" "  " "\x90\x94" "|" "\x89" "~" \
      "\xa5\x95\xb6\x90\x94" },
    { 23,  5, 0, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 185: menu 23 item 5 right */
    { 23,  5, 1,  1, 2, 0, 0x0000,
      "     30|     13 " },
    { 23,  5, 1,  8, 1, 7, 0x0000,
      "\x8e" "n" "\x93" "_" "\x8e" "w" "\x8e\xa6" \
      " (L)free (R)Read " },
    { 23,  5, 1, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 186: menu 23 item 6 left */
    { 23,  6, 0, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 187: menu 23 item 6 right */
    { 23,  6, 1,  8, 1, 7, 0x0000,
      "\x91\xe6\x82" "P" "\x82\xcc\x8c\xca\x8e" "n" "\x93" "_" \
      "\x8e" "w" "\x8e\xa6" " (L)free (R)Read |" "\x87" "@" \
      "\x90\xda\x82\xb7\x82\xe9\x8c\xca\xa5\x90\xfc" " " "\x8e" \
      "w" "\x92\xe8" "|" },
    /* branch 190: menu 23 item 8 left */
    { 23,  8, 0,  8, 1, 7, 0x0000,
      "\x89\xf0\x8f\x9c\x82\xb7\x82\xe9\x8b\xc8\x90\xfc\x82\xf0\x83" \
      "}" "\x83" "E" "\x83" "X" "\x8e" "w" "\x8e\xa6" " " },
    { 23,  8, 0, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 191: menu 23 item 8 right */
    { 23,  8, 1,  8, 1, 7, 0x0000,
      "\x89\xf0\x8f\x9c\x82\xb7\x82\xe9\x8b\xc8\x90\xfc\x82\xf0\x83" \
      "}" "\x83" "E" "\x83" "X" "\x8e" "w" "\x8e\xa6" " " },
    { 23,  8, 1, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 197: menu 24 item 2 left */
    { 24,  2, 0,  8, 1, 7, 0x0000,
      "\x82" "P" "\x96" "{" "\x90\xfc\xa5\x89" "~" \
      "\x95\xcf\x8d" "X " "\x83" "}" "\x83" "E" "\x83" "X" \
      "\x8e" "w" "\x8e\xa6" " |" "\x87" "@" "\x8e" "w" \
      "\x92\xe8\x94\xcd\x88\xcd\x93\xe0\x95\xcf\x8d" "X|" "\x87" \
      "A" "\x83\x8c\x83" "C" "\x83\x84\x95\xcf\x8d" "X" "\x81" \
      "y" "\x96\xb3\x81" "z|" "\x87" "B" \
      "\x91\xae\x90\xab\x90\xdd\x92\xe8" "|" },
    /* branch 202: menu 25 item 1 left */
    { 25,  1, 0,  1, 1, 7, 0x0000,
      "[ESC]  " },
    { 25,  1, 0,  8, 1, 7, 0x0000,
      "\x8f\xc1" " " "\x8b\x8e" "  " "\x8e" "n" "\x93" "_" \
      "\x83" "}" "\x83" "E" "\x83" "X" "\x8e" "w" "\x8e\xa6" " " },
    { 25,  1, 0, 30, 1, 7, 0x0000,
      "\x81" "i" },
    { 25,  1, 0, 32, 1, 7, 0x0000,
      "\x90\xfc\xa5\x89" "~" "\xa5\x95\xb6\x8e\x9a" },
    { 25,  1, 0, 42, 1, 7, 0x0000,
      "\x81" "j " },
    { 25,  1, 0, 45, 1, 7, 0x0000,
      "(L)free (R)Read " },
    /* branch 203: menu 25 item 1 right */
    { 25,  1, 1,  1, 1, 7, 0x0000,
      "[ESC]  " },
    { 25,  1, 1,  8, 1, 7, 0x0000,
      "\x8f\xc1" " " "\x8b\x8e" "  " "\x8e" "n" "\x93" "_" \
      "\x83" "}" "\x83" "E" "\x83" "X" "\x8e" "w" "\x8e\xa6" " " },
    { 25,  1, 1, 30, 1, 7, 0x0000,
      "\x81" "i" },
    { 25,  1, 1, 32, 1, 7, 0x0000,
      "\x90\xfc\xa5\x89" "~" "\xa5\x95\xb6\x8e\x9a" },
    { 25,  1, 1, 42, 1, 7, 0x0000,
      "\x81" "j " },
    { 25,  1, 1, 45, 1, 7, 0x0000,
      "(L)free (R)Read " },
    /* branch 204: menu 25 item 2 left */
    { 25,  2, 0,  1, 1, 7, 0x0000,
      "[ESC]  " },
    { 25,  2, 0,  8, 1, 7, 0x0000,
      "\x8f\xc1" " " "\x8b\x8e" "  " "\x8e" "n" "\x93" "_" \
      "\x83" "}" "\x83" "E" "\x83" "X" "\x8e" "w" "\x8e\xa6" " " },
    { 25,  2, 0, 30, 1, 7, 0x0000,
      "\x81" "i" },
    { 25,  2, 0, 32, 1, 7, 0x0000,
      "\x90\xfc\xa5\x89" "~" "\xa5\x95\xb6\x8e\x9a" },
    { 25,  2, 0, 45, 1, 7, 0x0000,
      "(L)free (R)Read " },
    /* branch 205: menu 25 item 2 right */
    { 25,  2, 1,  1, 1, 7, 0x0000,
      "[ESC]  " },
    { 25,  2, 1,  8, 1, 7, 0x0000,
      "\x8f\xc1" " " "\x8b\x8e" "  " "\x8e" "n" "\x93" "_" \
      "\x83" "}" "\x83" "E" "\x83" "X" "\x8e" "w" "\x8e\xa6" " " },
    { 25,  2, 1, 30, 1, 7, 0x0000,
      "\x81" "i" },
    { 25,  2, 1, 32, 1, 7, 0x0000,
      "\x90\xfc\xa5\x89" "~" "\xa5\x95\xb6\x8e\x9a" },
    { 25,  2, 1, 42, 1, 7, 0x0000,
      "\x81" "j " },
    { 25,  2, 1, 45, 1, 7, 0x0000,
      "(L)free (R)Read " },
    /* branch 211: menu 26 item 1 left */
    { 26,  1, 0,  1, 1, 7, 0x0000,
      "[ESC]" },
    { 26,  1, 0,  8, 1, 7, 0x0000,
      "\x90\xda\x90\xfc" " |" "\x87" "@" "\x89" "~" "\x81" "`" \
      "\x89" "~" "\x8a\xd4" " |" "\x87" "A" "\x89" "~" \
      "\x8e\xfc\x93" "_ |" "\x87" "B" "\x8e" "w" "\x92\xe8\x93" \
      "_ |" "\x87" "C" "\x8a" "p" "\x93" "x" "\x8e" "w" \
      "\x92\xe8" " |" },
    { 26,  1, 0, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 212: menu 26 item 1 right */
    { 26,  1, 1,  1, 1, 7, 0x0000,
      "[ESC]" },
    { 26,  1, 1,  8, 1, 7, 0x0000,
      "\x90\xda\x90\xfc" " |" "\x87" "@" "\x89" "~" "\x81" "`" \
      "\x89" "~" "\x8a\xd4" " |" "\x87" "A" "\x89" "~" \
      "\x8e\xfc\x93" "_ |" "\x87" "B" "\x8e" "w" "\x92\xe8\x93" \
      "_ |" "\x87" "C" "\x8a" "p" "\x93" "x" "\x8e" "w" \
      "\x92\xe8" " |" },
    { 26,  1, 1, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 213: menu 26 item 2 left */
    { 26,  2, 0,  8, 1, 7, 0x0000,
      "|" "\x87" "@" "\x82" "P" "\x90\xfc\x82" "P" "\x89" \
      "~(L)|" "\x87" "A" "\x82" "P" "\x93" "_" "\x82" "P" \
      "\x90\xfc" "(R)|" "\x87" "B" "\x82" "P" "\x89" "~" "\x82" \
      "P" "\x93" "_ |" "\x87" "C" "\x82" "Q" "\x90\xfc" " |" \
      "\x87" "D" "\x82" "Q" "\x89" "~ |" "\x87" "E" "\x82" "Q" \
      "\x93" "_ |" },
    { 26,  2, 0, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 214: menu 26 item 2 right */
    { 26,  2, 1,  8, 1, 7, 0x0000,
      "|" "\x87" "@" "\x82" "P" "\x90\xfc\x82" "P" "\x89" \
      "~(L)|" "\x87" "A" "\x82" "P" "\x93" "_" "\x82" "P" \
      "\x90\xfc" "(R)|" "\x87" "B" "\x82" "P" "\x89" "~" "\x82" \
      "P" "\x93" "_ |" "\x87" "C" "\x82" "Q" "\x90\xfc" " |" \
      "\x87" "D" "\x82" "Q" "\x89" "~ |" "\x87" "E" "\x82" "Q" \
      "\x93" "_ |" },
    { 26,  2, 1, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 215: menu 26 item 3 left */
    { 26,  3, 0,  8, 1, 7, 0x0000,
      "|" "\x87" "@ " "\x82" "R" "\x93" "_ |" "\x87" "A " "\x82" \
      "Q" "\x93" "_" "\x82\xc6\x82" "P" "\x90\xfc\xa5\x89" "~ |" \
      "\x87" "B " "\x82" "P" "\x93" "_" "\x82\xc6\x82" "Q" \
      "\x90\xfc\xa5\x89" "~ |" "\x87" "C " "\x82" "R" \
      "\x90\xfc\xa5\x89" "~ |" },
    { 26,  3, 0, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 216: menu 26 item 3 right */
    { 26,  3, 1,  8, 1, 7, 0x0000,
      "|" "\x87" "@ " "\x82" "R" "\x93" "_ |" "\x87" "A " "\x82" \
      "Q" "\x93" "_" "\x82\xc6\x82" "P" "\x90\xfc\xa5\x89" "~ |" \
      "\x87" "B " "\x82" "P" "\x93" "_" "\x82\xc6\x82" "Q" \
      "\x90\xfc\xa5\x89" "~ |" "\x87" "C " "\x82" "R" \
      "\x90\xfc\xa5\x89" "~ |" },
    { 26,  3, 1, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 217: menu 26 item 4 left */
    { 26,  4, 0, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 218: menu 26 item 4 right */
    { 26,  4, 1,  8, 1, 7, 0x0000,
      "\x90\xda\x91\xc8\x89" "~   |" "\x87" "@ " "\x82" "R" \
      "\x93" "_ |" "\x87" "A " "\x95" "H" "\x8c" "`" \
      "\x93\xe0\x90\xda" " |" "\x87" "B " "\x95\xbd\x8d" "s" \
      "\x8e" "l" "\x95\xd3\x8c" "`" "\x93\xe0\x90\xda" " |" },
    /* branch 241: menu 28 item 1 left */
    { 28,  1, 0,  8, 1, 7, 0x0000,
      "\x81" "y" "\x95\xcf\x8d" "X" "\x81" "z" \
      "\x95\xb6\x8e\x9a\x91" "I" "\x91\xf0" " |" "\x87" "@" \
      "\x8a\xee\x93" "_" "\x81" "i" "\x8d\xb6\x89\xba\x81" "j|" \
      "\x87" "A" "\x95\xb6\x98" "A" "\x8c\x8b\xa5\x90\xd8\x92" \
      "f |" "\x87" "B" "\x8b" "^" \
      "\x8e\x97\x90\xfc\x95\xb6\x8e\x9a" "|" },
    { 28,  1, 0, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 242: menu 28 item 1 right */
    { 28,  1, 1,  6, 1, 7, 0x0000,
      "\x81" "E" },
    { 28,  1, 1,  8, 1, 7, 0x0000,
      "\x81" "y" "\x95\xcf\x8d" "X" "\x81" "z" \
      "\x95\xb6\x8e\x9a\x91" "I" "\x91\xf0" " |" "\x87" "@" \
      "\x8a\xee\x93" "_" "\x81" "i" "\x8d\xb6\x89\xba\x81" "j|" \
      "\x87" "A" "\x95\xb6\x98" "A" "\x8c\x8b\xa5\x90\xd8\x92" \
      "f |" "\x87" "B" "\x8b" "^" \
      "\x8e\x97\x90\xfc\x95\xb6\x8e\x9a" "|" },
    { 28,  1, 1, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 243: menu 28 item 2 left */
    { 28,  2, 0,  6, 1, 7, 0x0000,
      "\x81" "E" },
    { 28,  2, 0,  8, 1, 7, 0x0000,
      "\x81" "q" "\x88\xda\x93\xae\x81" "r" \
      "\x95\xb6\x8e\x9a\x82\xf0\x91" "I" \
      "\x82\xf1\x82\xc5\x89\xba\x82\xb3\x82\xa2" " |" "\x87" "@" \
      "\x8a\xee\x93" "_(" "\x8d\xb6\x89\xba" ")|" "\x87" "A" \
      "\x81" "y" "\x94" "C" "\x88\xd3\x81" "z" \
      "\x95\xfb\x8c\xfc" "|" },
    { 28,  2, 0, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 244: menu 28 item 2 right */
    { 28,  2, 1,  6, 1, 7, 0x0000,
      "\x81" "E" },
    { 28,  2, 1,  8, 1, 7, 0x0000,
      "\x81" "q" "\x88\xda\x93\xae\x81" "r" \
      "\x95\xb6\x8e\x9a\x82\xf0\x91" "I" \
      "\x82\xf1\x82\xc5\x89\xba\x82\xb3\x82\xa2" " |" "\x87" "@" \
      "\x8a\xee\x93" "_(" "\x8d\xb6\x89\xba" ")|" "\x87" "A" \
      "\x81" "y" "\x94" "C" "\x88\xd3\x81" "z" \
      "\x95\xfb\x8c\xfc" "|" },
    { 28,  2, 1, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 245: menu 28 item 3 left */
    { 28,  3, 0,  6, 1, 7, 0x0000,
      "\x81" "E" },
    { 28,  3, 0,  8, 1, 7, 0x0000,
      "\x81" "s" "\x95\xa1\x8e\xca\x81" "t" \
      "\x95\xb6\x8e\x9a\x82\xf0\x91" "I" \
      "\x82\xf1\x82\xc5\x89\xba\x82\xb3\x82\xa2" " |" "\x87" "@" \
      "\x8a\xee\x93" "_(" "\x8d\xb6\x89\xba" ")|" "\x87" "A" \
      "\x81" "y" "\x94" "C" "\x88\xd3\x81" "z" \
      "\x95\xfb\x8c\xfc" "|" },
    { 28,  3, 0, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 246: menu 28 item 3 right */
    { 28,  3, 1,  6, 1, 7, 0x0000,
      "\x81" "E" },
    { 28,  3, 1,  8, 1, 7, 0x0000,
      "\x81" "s" "\x95\xa1\x8e\xca\x81" "t" \
      "\x95\xb6\x8e\x9a\x82\xf0\x91" "I" \
      "\x82\xf1\x82\xc5\x89\xba\x82\xb3\x82\xa2" " |" "\x87" "@" \
      "\x8a\xee\x93" "_(" "\x8d\xb6\x89\xba" ")|" "\x87" "A" \
      "\x81" "y" "\x94" "C" "\x88\xd3\x81" "z" \
      "\x95\xfb\x8c\xfc" "|" },
    { 28,  3, 1, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 253: menu 28 item 7 left */
    { 28,  7, 0,  6, 1, 7, 0x0000,
      "\x81" "E" },
    { 28,  7, 0,  8, 1, 7, 0x0000,
      "\x81" "m" "\x8f\xc1\x8b\x8e\x81" "n" \
      "\x95\xb6\x8e\x9a\x82\xf0\x91" "I" \
      "\x82\xf1\x82\xc5\x89\xba\x82\xb3\x82\xa2" " " },
    { 28,  7, 0, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 254: menu 28 item 7 right */
    { 28,  7, 1,  6, 1, 7, 0x0000,
      "\x81" "E" },
    { 28,  7, 1,  8, 1, 7, 0x0000,
      "\x81" "m" "\x8f\xc1\x8b\x8e\x81" "n" \
      "\x95\xb6\x8e\x9a\x82\xf0\x91" "I" \
      "\x82\xf1\x82\xc5\x89\xba\x82\xb3\x82\xa2" " " },
    { 28,  7, 1, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 262: menu 29 item 4 left */
    { 29,  4, 0,  8, 1, 7, 0x0000,
      "|" "\x87" "@" "\x92\xbc\x90\xfc\x90" "L" "\x8f" "k |" \
      "\x87" "A" "\x92\xbc\x90\xfc\x95\x94\x95\xaa\x8f\xc1" " |" \
      "\x87" "B" "\xc3\xde\xb0\xc0\x90\xae\x97\x9d" " |" "\x87" \
      "C" "\xda\xb2\xd4\x90\xae\x97\x9d" " |" "\x87" "D" \
      "\xb8\xde\xd9\xb0\xcc\xdf\x90\xae\x97\x9d" " |" },
    { 29,  4, 0, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 263: menu 29 item 4 right */
    { 29,  4, 1,  8, 1, 7, 0x0000,
      "|" "\x87" "@" "\x92\xbc\x90\xfc\x90" "L" "\x8f" "k |" \
      "\x87" "A" "\x92\xbc\x90\xfc\x95\x94\x95\xaa\x8f\xc1" " |" \
      "\x87" "B" "\xc3\xde\xb0\xc0\x90\xae\x97\x9d" " |" "\x87" \
      "C" "\xda\xb2\xd4\x90\xae\x97\x9d" " |" "\x87" "D" \
      "\xb8\xde\xd9\xb0\xcc\xdf\x90\xae\x97\x9d" " |" },
    { 29,  4, 1, 73, 1, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* branch 264: menu 29 item 5 left */
    { 29,  5, 0,  1, 1, 7, 0x0000,
      "[ESC]" },
    { 29,  5, 0,  8, 1, 7, 0x0000,
      "|" "\x87" "@" "\x8c\x9a\x95\xa8\x8d\x82\x82\xb3\xa5\x90" \
      "^" "\x96" "k " "\x90\xdd\x92\xe8" "|" "\x87" "A" \
      "\x93\xfa" " " "\x89" "e " "\x90" "}|" "\x87" "B" \
      "\x93\x99\x8e\x9e\x8a\xd4\x90" "}|" "\x87" "C" "\x8e" "w" \
      "\x92\xe8\x93" "_" "\x93\xfa\x89" "e" "\x8e\x9e\x8a\xd4" \
      "|" "\x87" "D" "\x95\xc7\x96\xca\x93\xfa\x89" "e|" },
    /* branch 265: menu 29 item 5 right */
    { 29,  5, 1,  1, 1, 7, 0x0000,
      "[ESC]" },
    { 29,  5, 1,  8, 1, 7, 0x0000,
      "|" "\x87" "@" "\x8c\x9a\x95\xa8\x8d\x82\x82\xb3\xa5\x90" \
      "^" "\x96" "k " "\x90\xdd\x92\xe8" "|" "\x87" "A" \
      "\x93\xfa" " " "\x89" "e " "\x90" "}|" "\x87" "B" \
      "\x93\x99\x8e\x9e\x8a\xd4\x90" "}|" "\x87" "C" "\x8e" "w" \
      "\x92\xe8\x93" "_" "\x93\xfa\x89" "e" "\x8e\x9e\x8a\xd4" \
      "|" "\x87" "D" "\x95\xc7\x96\xca\x93\xfa\x89" "e|" },
    /* branch 266: menu 29 item 6 left */
    { 29,  6, 0,  1, 1, 7, 0x0000,
      "[ESC]" },
    { 29,  6, 0,  8, 1, 7, 0x0000,
      "|" "\x87" "@" "\xd2\xd3\xd8\xb0\x94" "z" "\x95\xaa" "|" \
      "\x87" "A" "\x89\xe6\x96\xca\xbb\xb2\xbd\xde" "|" "\x87" \
      "B" "\xba\xcf\xdd\xc4\xde\xb7\xb0" "|" "\x87" "C" \
      "\x8d\xec\x90" "}" "\x8e\x9e\x8a\xd4" "|" "\x87" "D" \
      "\x8a\xc2\x8b\xab" "FILE|" "\x87" "E" \
      "\xc4\xde\xd7\xaf\xb8\xde\x97\xca" "|" "\x87" "F" \
      "\x89\xe6\x90" "F|" },
    /* branch 267: menu 29 item 6 right */
    { 29,  6, 1,  1, 1, 7, 0x0000,
      "[ESC]" },
    /* branch 277: menu 30 item 3 left */
    { 30,  3, 0,  1, 1, 7, 0x0000,
      "[ESC]" },
    { 30,  3, 0,  8, 1, 7, 0x0000,
      "\x83" "v" "\x83\x8a\x83\x93\x83" "^" "\x8b" "@" \
      "\x8e\xed" " |" "\x87" "@ " "\x82" "m" "\x82" "l " "\x8c" \
      "n |" "\x87" "A" "\x82" "o" "\x82" "b" "\x81\x5c\x82" "o" \
      "\x82" "q " "\x8c" "n |" "\x87" "B" "\x82" "d" "\x82" "r" \
      "\x82" "b" "\x81" "^" "\x82" "o |" "\x87" "C" "\x98" "g" \
      "\x8f\x91\x8d\x9e" "|" },
    /* branch 278: menu 30 item 3 right */
    { 30,  3, 1,  1, 1, 7, 0x0000,
      "[ESC]" },
    /* branch 281: menu 30 item 5 left */
    { 30,  5, 0,  1, 1, 7, 0x0000,
      "[ESC]" },
    { 30,  5, 0,  8, 1, 7, 0x0000,
      "\x95\xd2\x8f" "W" "\x92\x86\x82\xcc\x90" "}" \
      "\x96\xca\x82\xaa\x8e\xb8\x82\xed\x82\xea\x82\xdc\x82\xb7" \
      "  |" "\x87" "@" "\x90" "V" "\x8b" "K|" "\x87" "A" \
      "\x95\xdb\x91\xb6" "|" "\x87" "B" "\x92\x86\x8e" "~|" },
    /* branch 282: menu 30 item 5 right */
    { 30,  5, 1,  1, 1, 7, 0x0000,
      "[ESC]" },
    { 30,  5, 1,  8, 1, 7, 0x0000,
      "\x95\xd2\x8f" "W" "\x92\x86\x82\xcc\x90" "}" \
      "\x96\xca\x82\xaa\x8e\xb8\x82\xed\x82\xea\x82\xdc\x82\xb7" \
      "  |" "\x87" "@" "\x90" "V" "\x8b" "K|" "\x87" "A" \
      "\x95\xdb\x91\xb6" "|" "\x87" "B" "\x92\x86\x8e" "~|" },
    /* branch 283 (menu 30 item 6 left): the press wrote nothing */
    /* branch 284: menu 30 item 6 right */
    { 30,  6, 1,  8, 1, 7, 0x0000,
      "\x95\xd2\x8f" "W" "\x92\x86\x82\xcc\x90" "}" \
      "\x96\xca\x82\xaa\x8e\xb8\x82\xed\x82\xea\x82\xdc\x82\xb7" \
      "  |" "\x87" "@" "\x8f" "I" "\x97\xb9" "|" "\x87" "A" \
      "\x95\xdb\x91\xb6" "|" "\x87" "B" "\x92\x86\x8e" "~|" },
    { 0, 0, 0, 0, 0, 0, 0, 0 }
};

#endif
