/* src/optplan.h -- ｵﾌﾟｼｮﾝ ①建具平面's road, as the original writes it.
 *
 * Generated by tools/optplan_table.py out of what tools/optpick.sh captured.
 * Do not edit by hand -- run the two again.
 */
#ifndef JW_OPTPLAN_H
#define JW_OPTPLAN_H

/* Where the road is, once one of the sixteen shapes has been picked.
 * JwUi.opt_stage holds one of these. */
#define JW_OPT_PLAN   1         /* the sixteen shapes are up */
#define JW_OPT_BASE   2         /* a shape picked: 基準線(L) ２点(R) … */
#define JW_OPT_WHERE  3         /* a line picked: ◇位置 (L)free (R)Read … */
#define JW_OPT_BASE2  4         /* the same as BASE, once one has gone in */

typedef struct {
    int stage;
    int col, fg, bg;
    const char *text;
} JwOptPlan;

static const JwOptPlan JW_OPTPLAN[] = {
    /* press 1 */
    { 2,  6, 7, 0x0000,
      "\x81" "E" },
    { 2,  8, 7, 0x0000,
      "\x8a\xee\x8f\x80\x90\xfc" "(L) " "\x82" "Q" "\x93" \
      "_(R) |" "\x87" "@" "\x93\xe0\x96" "@" "\x90\xa1\x96" "@|" \
      "\x87" "A" \
      "\x8a\xee\x8f\x80\x90\xfc\x82\xc6\x82\xcc\x8a\xd4\x8a" \
      "u|" },
    { 2, 73, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    /* press 2 */
    { 3,  1, 7, 0x0000,
      "[ESC] " "\x81\x9e" },
    { 3,  9, 7, 0x0000,
      "\x88\xca\x92" "u" },
    { 3, 13, 7, 0x0000,
      " (L)free (R)Read|" "\x87" "@" "\x8a\xd4\x8a" "u" \
      "\x94\xbd\x93" "]|" "\x87" "A" "\x8c\x9a\x8b\xef\x90" "S" \
      "\x95\xcf" "|" "\x87" "B" "\x8a\xee\x8f\x80\x93" "_" \
      "\x95\xcf" "|" "\x87" "C" "\x8c\x9a\x8b\xef\x94\xbd\x93" \
      "]|" "\x87" "D" },
    { 3, 76, 7, 0x0000,
      "\x8d\xb6\x89" "E|" },
    /* press 3 */
    { 4,  1, 7, 0x0000,
      "[ESC]" },
    { 4,  6, 7, 0x0000,
      "\x81" "E" },
    { 4,  8, 7, 0x0000,
      "\x8a\xee\x8f\x80\x90\xfc" "(L) " "\x82" "Q" "\x93" \
      "_(R) |" "\x87" "@" "\x93\xe0\x96" "@" "\x90\xa1\x96" "@|" \
      "\x87" "A" \
      "\x8a\xee\x8f\x80\x90\xfc\x82\xc6\x82\xcc\x8a\xd4\x8a" \
      "u|" },
    { 4, 73, 7, 0x0000,
      "[BS]" "\x91" "O" "\x8d\x80" },
    { 0, 0, 0, 0, 0 }
};

#endif
