/* src/snapmsg.h -- what a modified read writes while it waits.

Generated by tools/snapmsg.py, out of the running original.

A press with [SHIFT] or [GRPH] held does not always take a point: it picks a
line or a circle, or a first point, and then asks again.  While it is asking,
the original **blacks the whole top line** and writes two pieces over it -- the
word [ESC] at column 1 and the mode's own line at column 8.  It blacks the
band beside the counts as well, x122 to x638 of y17..31, over the wipe and
the サーチ it wrote there; capture() says how that was settled.

The rows below are exactly what the original wrote, cell by cell.
 */
#ifndef JW_SNAPMSG_H
#define JW_SNAPMSG_H

/* One string and where it goes: column, row, both one-based. */
typedef struct {
    int mode;                   /* JwCmd.snap: JW_SNAP_ON or JW_SNAP_MID */
    int col, row;
    const char *text;
} JwSnapMsg;

static const JwSnapMsg JW_SNAPMSG[] = {
    { JW_SNAP_ON,  1, 1, "[ESC]" },
    { JW_SNAP_ON,  8, 1, "\x81" "y\x90" "\xfc" "\xa5" "\x89" "~\x8f" "\xe3" "\x93" "_\x83" "X\x83" "i\x83" "b\x83" "v\x81" "z (L)free (R)Read " },
    { JW_SNAP_MID,  1, 1, "[ESC]" },
    { JW_SNAP_MID,  8, 1, "\x81" "s\x82" "Q\x93" "_\x8a" "\xd4" "\x92" "\x86" "\x90" "S\x81" "t\x82" "a\x93" "_  (L)free (R)Read " },
    { 0, 0, 0, 0 },
};

#endif
