/* What a **modified** read would take, per command and per key.
 *
 * Generated by tools/snap_table.py.  Two strings in the band beside the
 * counts, at columns 17 and 22.  They go on last: a stage writes spaces at
 * column 17 on a black background, and those reach across column 22.
 *
 * They are there only while the pointer is over the drawing **and a modifier
 * key is held**.  With nothing held the original writes the spaces and leaves
 * the band black, so src/ui.c draws them only for the key that is down.  The
 * three rows are [SHIFT], [CTRL] and [GRPH], which JW_SNAP_KEY names; a 0
 * means the original wrote nothing there, and [SHIFT] and [GRPH] write one
 * string at column 17 wide enough to reach across column 22.
 *
 * The whole table looked unconditional until 2026-09-18: dosv_emu_cpp did not
 * answer INT 16h AH=12h, JW_CAD read the caller's own buffer as the shift
 * state, and the bit that came back set was Ctrl -- so every captured run
 * behaved as though Ctrl were held.  See RESUME.md 4.19.
 */
#ifndef JW_SNAP_H
#define JW_SNAP_H

/* The rows of JW_SNAP, in the order src/read.h's JW_MOD_* are worth naming. */
#define JW_SNAP_SHIFT 0
#define JW_SNAP_CTRL  1
#define JW_SNAP_GRPH  2

static const char *const JW_SNAP[3][30][2] = {
  {  /* shift */
    { 0, 0 },  /*  1 */
    { "\x90" "\xfc" "\x81" "E\x89" "~\x8f" "\xe3" "\x93" "_", 0 },  /*  2 */
    { "\x90" "\xfc" "\x81" "E\x89" "~\x8f" "\xe3" "\x93" "_", 0 },  /*  3 */
    { "\x90" "\xfc" "\x81" "E\x89" "~\x8f" "\xe3" "\x93" "_", 0 },  /*  4 */
    { 0, 0 },  /*  5 */
    { 0, 0 },  /*  6 */
    { 0, 0 },  /*  7 */
    { 0, 0 },  /*  8 */
    { 0, 0 },  /*  9 */
    { 0, 0 },  /* 10 */
    { "\x90" "\xfc" "\x81" "E\x89" "~\x8f" "\xe3" "\x93" "_", 0 },  /* 11 */
    { "\x90" "\xfc" "\x81" "E\x89" "~\x8f" "\xe3" "\x93" "_", 0 },  /* 12 */
    { "\x90" "\xfc" "\x81" "E\x89" "~\x8f" "\xe3" "\x93" "_", 0 },  /* 13 */
    { 0, 0 },  /* 14 */
    { "\x90" "\xfc" "\x81" "E\x89" "~\x8f" "\xe3" "\x93" "_", 0 },  /* 15 */
    { 0, 0 },  /* 16 */
    { 0, 0 },  /* 17 */
    { 0, 0 },  /* 18 */
    { 0, 0 },  /* 19 */
    { "\x90" "\xfc" "\x81" "E\x89" "~\x8f" "\xe3" "\x93" "_", 0 },  /* 20 */
    { 0, 0 },  /* 21 */
    { "\x90" "\xfc" "\x81" "E\x89" "~\x8f" "\xe3" "\x93" "_", 0 },  /* 22 */
    { 0, 0 },  /* 23 */
    { 0, 0 },  /* 24 */
    { 0, 0 },  /* 25 */
    { 0, 0 },  /* 26 */
    { 0, 0 },  /* 27 */
    { 0, 0 },  /* 28 */
    { 0, 0 },  /* 29 */
    { 0, 0 },  /* 30 */
  },
  {  /* ctrl */
    { 0, 0 },  /*  1 */
    { "\x89" "\x94" "\x92" "\xbc" "\xa5", "\x89" "~\x8e" "\xfc" "1/4\x93" "_" },  /*  2 */
    { "\x89" "\x94" "\x92" "\xbc" "\xa5", "\x89" "~\x8e" "\xfc" "\x93" "_" },  /*  3 */
    { "              ", "\x89" "~\x8e" "\xfc" "1/4\x93" "_" },  /*  4 */
    { 0, 0 },  /*  5 */
    { 0, 0 },  /*  6 */
    { 0, 0 },  /*  7 */
    { 0, 0 },  /*  8 */
    { 0, 0 },  /*  9 */
    { 0, 0 },  /* 10 */
    { "              ", "\x89" "~\x8e" "\xfc" "1/4\x93" "_" },  /* 11 */
    { "              ", "\x89" "~\x8e" "\xfc" "1/4\x93" "_" },  /* 12 */
    { "              ", "\x89" "~\x8e" "\xfc" "1/4\x93" "_" },  /* 13 */
    { 0, 0 },  /* 14 */
    { "              ", "\x89" "~\x8e" "\xfc" "1/4\x93" "_" },  /* 15 */
    { 0, 0 },  /* 16 */
    { 0, 0 },  /* 17 */
    { 0, 0 },  /* 18 */
    { 0, 0 },  /* 19 */
    { "              ", "\x89" "~\x8e" "\xfc" "1/4\x93" "_" },  /* 20 */
    { 0, 0 },  /* 21 */
    { "              ", "\x89" "~\x8e" "\xfc" "1/4\x93" "_" },  /* 22 */
    { 0, 0 },  /* 23 */
    { 0, 0 },  /* 24 */
    { 0, 0 },  /* 25 */
    { 0, 0 },  /* 26 */
    { 0, 0 },  /* 27 */
    { 0, 0 },  /* 28 */
    { 0, 0 },  /* 29 */
    { 0, 0 },  /* 30 */
  },
  {  /* alt */
    { 0, 0 },  /*  1 */
    { "\x92" "\x86" "\x90" "S\x93" "_\x81" "E\x82" "`\x93" "_", 0 },  /*  2 */
    { "\x92" "\x86" "\x90" "S\x93" "_\x81" "E\x82" "`\x93" "_", 0 },  /*  3 */
    { "\x92" "\x86" "\x90" "S\x93" "_\x81" "E\x82" "`\x93" "_", 0 },  /*  4 */
    { 0, 0 },  /*  5 */
    { 0, 0 },  /*  6 */
    { 0, 0 },  /*  7 */
    { 0, 0 },  /*  8 */
    { 0, 0 },  /*  9 */
    { 0, 0 },  /* 10 */
    { "\x92" "\x86" "\x90" "S\x93" "_\x81" "E\x82" "`\x93" "_", 0 },  /* 11 */
    { "\x92" "\x86" "\x90" "S\x93" "_\x81" "E\x82" "`\x93" "_", 0 },  /* 12 */
    { "\x92" "\x86" "\x90" "S\x93" "_\x81" "E\x82" "`\x93" "_", 0 },  /* 13 */
    { 0, 0 },  /* 14 */
    { "\x92" "\x86" "\x90" "S\x93" "_\x81" "E\x82" "`\x93" "_", 0 },  /* 15 */
    { 0, 0 },  /* 16 */
    { 0, 0 },  /* 17 */
    { 0, 0 },  /* 18 */
    { 0, 0 },  /* 19 */
    { "\x92" "\x86" "\x90" "S\x93" "_\x81" "E\x82" "`\x93" "_", 0 },  /* 20 */
    { 0, 0 },  /* 21 */
    { "\x92" "\x86" "\x90" "S\x93" "_\x81" "E\x82" "`\x93" "_", 0 },  /* 22 */
    { 0, 0 },  /* 23 */
    { 0, 0 },  /* 24 */
    { 0, 0 },  /* 25 */
    { 0, 0 },  /* 26 */
    { 0, 0 },  /* 27 */
    { 0, 0 },  /* 28 */
    { 0, 0 },  /* 29 */
    { 0, 0 },  /* 30 */
  },
};

#endif
