/* What a drawing command writes while it runs.
 *
 * Generated by tools/stage_table.py out of what tools/press.sh captured: the
 * emulator picks the item and presses the points, and what the original wrote
 * after each press is kept.  Do not edit by hand -- run the tool again.
 *
 * Each stage is what that press wrote.  The original clears the top line as it
 * moves on, so what the stage before left there is gone; src/ui.c does the same.
 *
 * The numbers are the drawing being made -- the length and the angle for a
 * line, the two sides for a box, the radius and the diameter for a circle -- so
 * they are here as `%%*.*f` and src/ui.c fills in the value, the width it had
 * and how many decimals the drawing's scale calls for.
 */
#ifndef JW_STAGE_H
#define JW_STAGE_H

typedef struct {
    int command;                /* the menu item, or 0 to end the table */
    int stage;                  /* 1 = a point taken, 2 = the thing is drawn */
    int col, row, fg, bg;
    int numbers;                /* how many %*.*f the text has */
    int first;                  /* which of the command's numbers the first one
                                 * is: the row under the counts carries the
                                 * second (角度, 縦, 直径), every other row the
                                 * first */
    int width[2];               /* the field width each of them had */
    const char *text;
} JwStage;

static const JwStage JW_STAGE[] = {
    {  2, 1,  1, 2, 0, 0x0000, 1, 0, { 10, 0 }, " \x92" "\xb7" "=%*.*f " },
    {  2, 1,  1, 3, 0, 0x0000, 1, 1, { 8, 0 }, " \x8a" "p\x93" "x=%*.*f\xdf" " " },
    {  2, 1,  1, 1, 7, 0x0000, 0, 0, { 0, 0 }, "[ESC]\x81" "E\x81" "\x9f" "\x8f" "I\x93" "_\x8e" "w\x8e" "\xa6" " (L)free (R)Read |\x87" "@  \x81" "^  |\x87" "A\x90" "\xa1" " \x96" "@ |\x87" "B\x8a" "p \x93" "x |\x87" "C \x95" "\xbd" " \x8d" "s\x81" "E\x90" "\x82" " \x92" "\xbc" "  |" },
    {  2, 2,  1, 1, 7, 0x0000, 0, 0, { 0, 0 }, "[ESC]" },
    {  2, 2,  6, 1, 7, 0x0000, 0, 0, { 0, 0 }, "\x81" "E" },
    {  2, 2,  8, 1, 7, 0x0000, 2, 0, { 10, 8 }, "\x8e" "n\x93" "_\x8e" "w\x8e" "\xa6" " (L)free (R)Read \x8a" "m\x92" "\xe8" "\x92" "\xb7" "\x82" "\xb3" " =%*.*f(mm)\x8a" "p\x93" "x=%*.*f\xdf" },
    {  2, 2, 73, 1, 7, 0x0000, 0, 0, { 0, 0 }, "[BS]\x91" "O\x8d" "\x80" },
    {  3, 1,  1, 2, 0, 0x0000, 1, 0, { 10, 0 }, " \x92" "\xb7" "=%*.*f " },
    {  3, 1,  1, 3, 0, 0x0000, 1, 1, { 8, 0 }, " \x8a" "p\x93" "x=%*.*f\xdf" " " },
    {  3, 1,  1, 1, 7, 0x0000, 0, 0, { 0, 0 }, "[ESC]\x81" "E\x81" "\x9f" "\x8f" "I\x93" "_\x8e" "w\x8e" "\xa6" " (L)free (R)Read |\x87" "@  \x81" "{  |\x87" "A\x90" "\xa1" " \x96" "@ |\x87" "B\x8a" "p \x93" "x |\x87" "C\x95" "\xbd" " \x8d" "s |\x87" "D\x90" "\x82" " \x92" "\xbc" " |" },
    {  3, 2,  1, 1, 7, 0x0000, 0, 0, { 0, 0 }, "[ESC]" },
    {  3, 2,  6, 1, 7, 0x0000, 0, 0, { 0, 0 }, "\x81" "E" },
    {  3, 2,  8, 1, 7, 0x0000, 2, 0, { 10, 8 }, "\x8e" "n\x93" "_\x8e" "w\x8e" "\xa6" " (L)free (R)Read \x8a" "m\x92" "\xe8" "\x92" "\xb7" "\x82" "\xb3" " =%*.*f(mm)\x8a" "p\x93" "x=%*.*f\xdf" },
    {  3, 2, 73, 1, 7, 0x0000, 0, 0, { 0, 0 }, "[BS]\x91" "O\x8d" "\x80" },
    {  4, 1,  1, 2, 0, 0x0000, 1, 0, { 10, 0 }, " \x89" "\xa1" "=%*.*f " },
    {  4, 1,  1, 3, 0, 0x0000, 1, 1, { 10, 0 }, " \x8f" "c=%*.*f " },
    {  4, 1,  1, 1, 7, 0x0000, 0, 0, { 0, 0 }, "[ESC]" },
    {  4, 1,  6, 1, 7, 0x0000, 0, 0, { 0, 0 }, "\x81" "E" },
    {  4, 1,  8, 1, 7, 0x0000, 0, 0, { 0, 0 }, "\x81" "\xa1" " \x8f" "I\x93" "_\x8e" "w\x8e" "\xa6" " (L)free (R)Read |\x87" "@\x90" "\xa1" " \x96" "@ |\x87" "A\x8a" "p \x93" "x |\x87" "B\x95" "\xbd" " \x8d" "s |\x87" "C\x8a" "\xee" "\x93" "_\x95" "\xcf" "    |" },
    {  4, 2,  1, 1, 7, 0x0000, 0, 0, { 0, 0 }, "[ESC]" },
    {  4, 2,  6, 1, 7, 0x0000, 0, 0, { 0, 0 }, "\x81" "E" },
    {  4, 2,  8, 1, 7, 0x0000, 2, 0, { 10, 10 }, "\x8e" "n\x93" "_\x8e" "w\x8e" "\xa6" " (L)free (R)Read  \x8a" "m\x92" "\xe8" "\x90" "\xa1" "\x96" "@=%*.*f ,%*.*f mm" },
    {  4, 2, 73, 1, 7, 0x0000, 0, 0, { 0, 0 }, "[BS]\x91" "O\x8d" "\x80" },
    { 10, 1,  1, 1, 7, 0x0000, 0, 0, { 0, 0 }, "[ESC]" },
    { 10, 1,  6, 1, 7, 0x0000, 0, 0, { 0, 0 }, "\x81" "E" },
    { 10, 1,  8, 1, 7, 0x0000, 0, 0, { 0, 0 }, " \x90" "\xfc" ",\x89" "~\x8c" "\xca" "\x82" "\xf0" "\x83" "}\x83" "E\x83" "X\x8e" "w\x8e" "\xa6" "   \x95" "\x94" "\x95" "\xaa" "\x8f" "\xc1" "\x8b" "\x8e" " \xcf" "\xb3" "\xbd" "(L)   \x8f" "\xc1" "\x8b" "\x8e" "\x81" "i\x8e" "\xc0" "\x93" "_\x8a" "\xdc" "\x82" "\xde" "\x81" "j\xcf" "\xb3" "\xbd" "(R) " },
    { 11, 1,  1, 2, 0, 0x0000, 1, 0, { 10, 0 }, "\x94" "\xbc" "\x8c" "a=%*.*f  " },
    { 11, 1,  1, 3, 0, 0x0000, 1, 1, { 10, 0 }, "\x92" "\xbc" "\x8c" "a=%*.*f  " },
    { 11, 1,  1, 1, 7, 0x0000, 0, 0, { 0, 0 }, "[ESC]" },
    { 11, 1,  6, 1, 7, 0x0000, 0, 0, { 0, 0 }, " \x81" "\x9c" " \x89" "~\x88" "\xca" "\x92" "u\x8e" "w\x8e" "\xa6" " (L)free (R)Read " },
    { 11, 1, 37, 1, 7, 0x0000, 0, 0, { 0, 0 }, "|\x87" "@ \x8c" "a\x8e" "w\x92" "\xe8" "  |\x87" "A\x8a" "\xee" "\x93" "_\x95" "\xcf" "   |\x87" "B(1)\x8f" "d\x89" "~  |" },
    { 11, 2,  1, 1, 7, 0x0000, 0, 0, { 0, 0 }, "[ESC]" },
    { 11, 2,  6, 1, 7, 0x0000, 0, 0, { 0, 0 }, "\x81" "E" },
    { 11, 2,  8, 1, 7, 0x0000, 1, 0, { 10, 0 }, "\x81" "\x9b" " \x89" "~\x92" "\x86" "\x90" "S\x93" "_ \x83" "}\x83" "E\x83" "X\x8e" "w\x8e" "\xa6" " (L)free (R)Read \x94" "\xbc" "\x8c" "a=%*.*f " },
    { 11, 2, 73, 1, 7, 0x0000, 0, 0, { 0, 0 }, "[BS]\x91" "O\x8d" "\x80" },
    { 22, 1,  1, 1, 7, 0x0000, 0, 0, { 0, 0 }, "[ESC]" },
    { 22, 1,  6, 1, 7, 0x0000, 0, 0, { 0, 0 }, "\x81" "E" },
    { 22, 1,  8, 1, 7, 0x0000, 0, 0, { 0, 0 }, "\x93" "_ \x88" "\xca" "\x92" "u\x8e" "w\x8e" "\xa6" "(L)free (R)Read |\x87" "@\x81" "y\x89" "\xbc" "\x93" "_\x81" "z|\x87" "A\x8b" "\x97" "\x97" "\xa3" "|\x87" "B\x8c" "\xf0" "\x93" "_|\x87" "C\x89" "~\x92" "\x86" "\x90" "S|\x87" "D\x89" "\xbc" "\x93" "_\x8d" "\xed" "\x8f" "\x9c" "|" },
    { 0, 0, 0, 0, 0, 0, 0, 0, { 0, 0 }, 0 },
};

#endif
