/* src/zukei.h -- 図形's registration road, as the original writes it.
 *
 * Generated by tools/zukei_table.py out of what tools/zukei.sh captured.
 * Do not edit by hand -- run the two again.
 *
 * `orig/JW_CADV.HLP` (図 形 その1/4) says what the road is; this is what the
 * original puts on the top line at each step of it.
 */
#ifndef JW_ZUKEI_H
#define JW_ZUKEI_H

/* The steps of 図形 ①登録, which are the presses tools/zukei.sh makes.
 * JwCmd.zukei holds one of these once the item has been pressed. */
#define JW_ZUKEI_RANGE  1       /* 図形範囲 始点マウス指示 */
#define JW_ZUKEI_BASE   3       /* ◇原図形の基準点位置 */
#define JW_ZUKEI_PICK   5       /* ◇ 図形選択 |①選択確定 |… */
#define JW_ZUKEI_NAME   6       /* 図形 登録 ◆図形名入力 */
#define JW_ZUKEI_WRITE  7       /* 書き込みます |① 実 行(L)|② 再選択(R)| */
#define JW_ZUKEI_DONE   8

typedef struct {
    int stage;                  /* which press, 1 to 8; 0 ends the table */
    int col, fg, bg;
    const char *text;
} JwZukei;

static const JwZukei JW_ZUKEI[] = {
    /* press 1 */
    { 1,  1, 7, 0x0000,
      "[ESC]  " },
    { 1,  8, 7, 0x0000,
      "\x90" "}" "\x8c" "`" "\x94\xcd\x88\xcd" "  " "\x8e" "n" \
      "\x93" "_" "\x83" "}" "\x83" "E" "\x83" "X" "\x8e" "w" \
      "\x8e\xa6" " " },
    { 1, 33, 7, 0x0000,
      "(L)" "\x90\xfc\xa5\x89" "~ " },
    { 1, 42, 7, 0x0000,
      " (R)" },
    { 1, 46, 7, 0x0000,
      "\x90\xfc\xa5\x89" "~" "\xa5\x95\xb6\x8e\x9a" },
    { 1, 56, 7, 0x0000,
      "  [F1" "\x81" "`F10] " },
    { 1, 68, 7, 0x0000,
      "|" "\x87" "@ " "\x91" "O " "\x94\xcd" " " "\x88\xcd" "|" },
    /* press 2 */
    { 2,  1, 7, 0x0000,
      "[ESC]  " },
    { 2,  8, 7, 0x0000,
      "<" "\x90\xfc\xa5\x89" "~>" },
    { 2, 15, 7, 0x0000,
      "  " },
    { 2, 17, 7, 0x0000,
      "\x8f" "I" "\x93" "_" "\x8e" "w" "\x8e\xa6" " " },
    { 2, 26, 7, 0x0000,
      "\xcf\xb3\xbd" "(L) " },
    { 2, 33, 7, 0x0000,
      " " "\x94\xcd\x88\xcd\x8a" "m" "\x92\xe8" " " },
    { 2, 43, 7, 0x0000,
      "\xcf\xb3\xbd" "(R) " },
    { 2, 53, 7, 0x0000,
      "|" },
    { 2, 54, 7, 0x0000,
      "\x87" "@" },
    { 2, 56, 7, 0x0000,
      "\x83\x8c\x83" "C" "\x83\x84" },
    { 2, 62, 7, 0x0000,
      "|" },
    { 2, 63, 7, 0x0000,
      "\x87" "A" },
    { 2, 65, 7, 0x0000,
      "\x90\xfc\x8e\xed\x90" "F" },
    { 2, 71, 7, 0x0000,
      "|" },
    /* press 3 */
    { 3,  1, 7, 0x0000,
      "[ESC]" },
    { 3,  8, 7, 0x0000,
      "\x81\x9e\x8c\xb4\x90" "}" "\x8c" "`" \
      "\x82\xcc\x8a\xee\x8f\x80\x93" "_" "\x88\xca\x92" "u " \
      "\x83" "}" "\x83" "E" "\x83" "X" "\x8e" "w" "\x8e\xa6" \
      " (L)free (R)Read " },
    /* press 5 */
    { 5,  1, 7, 0x0000,
      "[ESC]" },
    { 5,  8, 7, 0x0000,
      "\x81\x9e" " " "\x90" "}" "\x8c" "`" "\x91" "I" "\x91\xf0" \
      " " "\x83" "}" "\x83" "E" "\x83" "X" "\x8e" "w" "\x8e\xa6" \
      " |" "\x87" "@" "\x91" "I" "\x91\xf0\x8a" "m" "\x92\xe8" \
      " |" "\x87" "A" "\x83" "h" "\x83\x89\x83" "C" "\x83" \
      "u(A:)" "\x95\xcf\x8d" "X|" "\x87" "B" "\x83" "O" \
      "\x83\x8b\x81" "[" "\x83" "v" "\x95\xcf\x8d" "X|" },
    /* press 6 */
    { 6,  1, 7, 0x0000,
      "[ESC]   " "\x90" "}" "\x8c" "` " "\x93" "o" "\x98" "^  " \
      "\x81\x9f\x90" "}" "\x8c" "`" "\x96\xbc\x93\xfc\x97\xcd" \
      " : " },
    { 6, 34, 7, 0x0000,
      "" },
    { 6, 34, 7, 0x0000,
      " " },
    { 6, 35, 7, 0x0000,
      " " },
    { 6, 36, 7, 0x0000,
      " " },
    { 6, 37, 7, 0x0000,
      " " },
    { 6, 38, 7, 0x0000,
      " " },
    { 6, 39, 7, 0x0000,
      " " },
    { 6, 40, 7, 0x0000,
      " " },
    { 6, 41, 7, 0x0000,
      " " },
    { 6, 42, 7, 0x0000,
      " " },
    /* press 7 */
    { 7, 34, 7, 0x0000,
      "BOX" },
    { 7, 37, 7, 0x0000,
      " " },
    { 7, 38, 7, 0x0000,
      " " },
    { 7, 39, 7, 0x0000,
      " " },
    { 7, 40, 7, 0x0000,
      " " },
    { 7, 41, 7, 0x0000,
      " " },
    { 7, 42, 7, 0x0000,
      " " },
    { 7,  1, 7, 0x0000,
      "[ESC]" },
    { 7,  8, 7, 0x0000,
      "\x8f\x91\x82\xab\x8d\x9e\x82\xdd\x82\xdc\x82\xb7" " |" \
      "\x87" "@ " "\x8e\xc0" " " "\x8d" "s(L)|" "\x87" "A " \
      "\x8d\xc4\x91" "I" "\x91\xf0" "(R)|" },
    /* press 8 */
    { 8,  8, 7, 0x0000,
      "|" "\x87" "@" "\x93" "o" "\x98" "^|" "\x87" "A" \
      "\x93\xc7\x8d\x9e" "|" "\x87" "B" "\x95\x5c\x8e\xa6" "|" \
      "\x87" "C" "\xb8\xde\xd9\xb0\xcc\xdf\x95\xcf" "|" "\x87" \
      "D" "\x8d\xed\x8f\x9c" "|" "\x87" "E" "\xda\xb2\xd4" \
      " |   <" "\x91\xbc\x90" "}" "\x96\xca" ">|" "\x87" "F" \
      "\x93" "o" "\x98" "^|" "\x87" "G" "\x95\xa1\x8e\xca" "|" },
    { 0, 0, 0, 0, 0 }
};

#endif
